using ParcelWorkflowAddIn.Tests.CaseFolders;
using ParcelWorkflowAddIn.Tests.Innola;
using ParcelWorkflowAddIn.Tests.Intake;
using ParcelWorkflowAddIn.Tests.Preflight;
using ParcelWorkflowAddIn.Tests.Workflow;

var tests = new (string Name, Action Run)[]
{
    ("case folder creation creates required layout and manifest", CaseFolderStoreTests.CreateCaseCreatesLayoutAndManifest),
    ("case folder creation accepts innola transaction number", CaseFolderStoreTests.CreateCaseAcceptsInnolaTransactionNumber),
    ("case folder creation rejects duplicates", CaseFolderStoreTests.CreateCaseRejectsDuplicateTransactionFolder),
    ("case folder creation rejects unsafe transaction ids", CaseFolderStoreTests.CreateCaseRejectsUnsafeTransactionIds),
    ("case folder creation returns failure for invalid output root", CaseFolderStoreTests.CreateCaseReturnsFailureForInvalidOutputRoot),
    ("case folder reopen loads manifest state and artifacts", CaseFolderStoreTests.ReopenCaseFolderLoadsManifestStateAndArtifacts),
    ("case folder reopen reports missing manifest", CaseFolderStoreTests.ReopenCaseFolderReportsMissingManifest),
    ("case folder reopen reports corrupt manifest", CaseFolderStoreTests.ReopenCaseFolderReportsCorruptManifest),
    ("case folder reopen reports missing copied source files", CaseFolderStoreTests.ReopenCaseFolderReportsMissingCopiedSourceFiles),
    ("case folder reopen reports unknown workflow state", CaseFolderStoreTests.ReopenCaseFolderReportsUnknownWorkflowState),
    ("source file copy copies accepted files and updates manifest", SourceFileCopyServiceTests.CopySourceFilesCopiesAcceptedFilesAndUpdatesManifest),
    ("source file copy rejects unsupported extensions", SourceFileCopyServiceTests.CopySourceFilesRejectsUnsupportedExtensions),
    ("source file copy does not overwrite duplicate filenames", SourceFileCopyServiceTests.CopySourceFilesDoesNotOverwriteDuplicateFileNames),
    ("source file action opens copied path", SourceFileActionServiceTests.OpenUsesCopiedCaseFolderPath),
    ("source file action reveals copied path", SourceFileActionServiceTests.RevealUsesCopiedCaseFolderPath),
    ("source file action missing file returns non-blocking failure", SourceFileActionServiceTests.MissingCopiedFileReturnsNonBlockingFailure),
    ("source file action blocks tampered paths", SourceFileActionServiceTests.TamperedCopiedPathOutsideSourceDirectoryIsBlocked),
    ("source file action reports map route unavailable", SourceFileActionServiceTests.DwgTifAndTiffAreMapRouteCandidatesWithUnavailableStatus),
    ("source file action audit requires identity", SourceFileActionServiceTests.AuditIsWrittenOnlyWhenOperatorIdentityIsAvailable),
    ("source input profile detects scenario a", SourceInputProfileDetectorTests.DetectsScenarioAFromComputationAndPlanRoles),
    ("source input profile detects scenario b", SourceInputProfileDetectorTests.DetectsScenarioBFromPointsDwgAndPlanRoles),
    ("source input profile detects incomplete intake", SourceInputProfileDetectorTests.DetectsIncompleteIntakeWithMissingRoles),
    ("source input profile infers txt csv as points computation", SourceInputProfileDetectorTests.InfersTxtCsvAsPointsComputationWithoutFilenameHints),
    ("source input profile detects unsupported intake", SourceInputProfileDetectorTests.DetectsUnsupportedIntakeWithoutClaimingScenario),
    ("source input profile treats dwg only as incomplete", SourceInputProfileDetectorTests.DwgOnlyIntakeIsIncompleteWithScenarioBMissingRoles),
    ("source input profile labels avoid fixture case names", SourceInputProfileDetectorTests.ProductionLabelsNeverExposeFixtureCaseLabels),
    ("manifest preflight passes valid scenario a", ManifestPreflightServiceTests.ManifestPreflightPassesValidScenarioA),
    ("manifest preflight passes valid scenario b", ManifestPreflightServiceTests.ManifestPreflightPassesValidScenarioB),
    ("manifest preflight blocks missing detected profile", ManifestPreflightServiceTests.ManifestPreflightBlocksMissingDetectedProfile),
    ("manifest preflight blocks missing required role", ManifestPreflightServiceTests.ManifestPreflightBlocksMissingRequiredRole),
    ("manifest preflight blocks missing copied file", ManifestPreflightServiceTests.ManifestPreflightBlocksMissingCopiedFile),
    ("manifest preflight blocks unsupported extension", ManifestPreflightServiceTests.ManifestPreflightBlocksUnsupportedExtension),
    ("manifest preflight blocks tampered copied path", ManifestPreflightServiceTests.ManifestPreflightBlocksTamperedCopiedPath),
    ("manifest preflight summary uses snake case groups", ManifestPreflightServiceTests.ManifestPreflightSummaryUsesSnakeCaseGroups),
    ("manifest preflight hash ignores workflow state", ManifestPreflightServiceTests.ManifestPreflightHashIgnoresWorkflowState),
    ("environment preflight contributes passed checks to summary", ProcessingEnvironmentPreflightServiceTests.EnvironmentProbeContributesPassedChecksToSummary),
    ("environment preflight missing python executable blocks", ProcessingEnvironmentPreflightServiceTests.MissingPythonExecutableCreatesBlocker),
    ("environment preflight accepts sidwell python path from fake probe", ProcessingEnvironmentPreflightServiceTests.SidwellPythonPathIsAcceptedWhenFakeProbeReportsAvailable),
    ("environment preflight missing arcpy blocks", ProcessingEnvironmentPreflightServiceTests.MissingArcPyIsRequiredBlocker),
    ("environment preflight optional package missing warns", ProcessingEnvironmentPreflightServiceTests.OptionalPackageMissingIsWarning),
    ("environment preflight arcgis pro 3.7 compatible with 3.6 lane", ProcessingEnvironmentPreflightServiceTests.ArcGisPro37IsCompatibleWithConfigured36Lane),
    ("environment preflight arcgis pro assembly 13.6 compatible with 3.6 lane", ProcessingEnvironmentPreflightServiceTests.ArcGisProAssembly136IsCompatibleWithConfigured36Lane),
    ("environment preflight arcgis pro 3.5 incompatible with 3.6 lane", ProcessingEnvironmentPreflightServiceTests.ArcGisPro35IsNotCompatibleWithConfigured36Lane),
    ("environment preflight python timeout is sanitized", ProcessingEnvironmentPreflightServiceTests.PythonTimeoutIsSanitizedBlocker),
    ("environment preflight async prevents duplicate run", ProcessingEnvironmentPreflightServiceTests.WorkflowSessionAsyncPreflightPreventsDuplicateRun),
    ("environment preflight reopen shows environment checks", ProcessingEnvironmentPreflightServiceTests.ReopenShowsEnvironmentChecks),
    ("environment preflight does not create downstream artifacts", ProcessingEnvironmentPreflightServiceTests.EnvironmentPreflightDoesNotCreateDownstreamArtifacts),
    ("workflow session starts at no_case", WorkflowSessionTests.WorkflowSessionStartsAtNoCase),
    ("workflow session exposes intake state after creation", WorkflowSessionTests.WorkflowSessionExposesIntakeStateAfterCreation),
    ("workflow session exposes validation failure status", WorkflowSessionTests.WorkflowSessionExposesValidationFailureStatus),
    ("workflow session rejects source files without active case", WorkflowSessionTests.WorkflowSessionRejectsSourceFilesWithoutActiveCase),
    ("workflow session adds source files during intake", WorkflowSessionTests.WorkflowSessionAddsSourceFilesDuringIntake),
    ("workflow session exposes rejected source file rows", WorkflowSessionTests.WorkflowSessionExposesRejectedSourceFileRows),
    ("workflow session persists detected profile without removing source files", WorkflowSessionTests.WorkflowSessionPersistsDetectedProfileWithoutRemovingSourceFiles),
    ("workflow session reopens valid case folder", WorkflowSessionTests.WorkflowSessionReopensValidCaseFolder),
    ("workflow session reopens case with missing detected profile issue", WorkflowSessionTests.WorkflowSessionReopensCaseWithMissingDetectedProfileIssue),
    ("workflow session reports reopen failures without replacing active case", WorkflowSessionTests.WorkflowSessionReportsReopenFailuresWithoutReplacingActiveCase),
    ("workflow session does not create processing artifacts during reopen", WorkflowSessionTests.WorkflowSessionDoesNotCreateProcessingArtifactsDuringReopen),
    ("workflow session clears reopened case state when creating new case", WorkflowSessionTests.WorkflowSessionClearsReopenedCaseStateWhenCreatingNewCase),
    ("workflow session source actions work after reopen", WorkflowSessionTests.WorkflowSessionSourceActionsWorkAfterReopen),
    ("workflow session source action failures are non-blocking", WorkflowSessionTests.WorkflowSessionSourceActionFailuresAreNonBlocking),
    ("workflow session source actions audit and avoid processing artifacts", WorkflowSessionTests.WorkflowSessionSourceActionsAuditAndAvoidProcessingArtifacts),
    ("workflow session source action succeeds when existing audit is corrupt", WorkflowSessionTests.WorkflowSessionSourceActionSucceedsWhenExistingAuditIsCorrupt),
    ("workflow session run manifest preflight blocks missing role", WorkflowSessionTests.WorkflowSessionRunManifestPreflightBlocksMissingRole),
    ("workflow session run manifest preflight can pass manifest layer", WorkflowSessionTests.WorkflowSessionRunManifestPreflightCanPassManifestLayer),
    ("workflow session adding source after preflight invalidates preflight", WorkflowSessionTests.WorkflowSessionAddingSourceAfterPreflightInvalidatesPreflight),
    ("workflow session refreshing profile after preflight invalidates preflight", WorkflowSessionTests.WorkflowSessionRefreshingProfileAfterPreflightInvalidatesPreflight),
    ("workflow session run manifest preflight handles corrupt manifest", WorkflowSessionTests.WorkflowSessionRunManifestPreflightHandlesCorruptManifest),
    ("workflow session reopens preflight artifact without downstream commands", WorkflowSessionTests.WorkflowSessionReopensPreflightArtifactWithoutDownstreamCommands)
    ,
    ("innola session starts logged out with safe gates", InnolaSessionManagerTests.SessionStartsLoggedOutWithSafeGates),
    ("innola successful login stores session in memory and enables transactions", () => InnolaSessionManagerTests.SuccessfulLoginStoresSessionInMemoryAndEnablesTransactions().GetAwaiter().GetResult()),
    ("innola failed login does not create session and keeps non-secret error", () => InnolaSessionManagerTests.FailedLoginDoesNotCreateSessionAndKeepsNonSecretError().GetAwaiter().GetResult()),
    ("innola logout clears session secrets and disables gates", () => InnolaSessionManagerTests.LogoutClearsSessionSecretsAndDisablesGates().GetAwaiter().GetResult()),
    ("innola session expiry clears session secrets and disables gates", InnolaSessionManagerTests.SessionExpiryClearsSessionSecretsAndDisablesGates),
    ("innola session secrets are not written to settings or case folder files", () => InnolaSessionManagerTests.SessionSecretsAreNotWrittenToSettingsOrCaseFolderFiles().GetAwaiter().GetResult()),
    ("innola auth maps user and group context from response", () => InnolaAuthServiceTests.LoginMapsUserAndGroupContextFromResponse().GetAwaiter().GetResult()),
    ("innola session manager raises login change on caller context", () => InnolaAuthServiceTests.SessionManagerRaisesLoginChangeOnCallerContext().GetAwaiter().GetResult()),
    ("innola mock auth enables dry run login", () => InnolaAuthServiceTests.MockAuthEnablesDryRunLogin().GetAwaiter().GetResult()),
    ("innola certificate settings map from workflow settings", InnolaTransactionSettingsTests.CertificateSettingsMapFromWorkflowSettings),
    ("innola transaction service maps prior payload and filters unavailable rows", InnolaTransactionServiceTests.MapsPriorInnolaTaskPayloadAndFiltersUnavailableRows),
    ("innola transaction service uses workflow my-tasks endpoint", () => InnolaTransactionServiceTests.HttpTransactionServiceUsesWorkflowMyTasksEndpoint().GetAwaiter().GetResult()),
    ("innola mock transaction service requires session and filters rows", () => InnolaTransactionServiceTests.MockTransactionServiceRequiresSessionAndFiltersRows().GetAwaiter().GetResult()),
    ("innola transaction errors redact secrets", () => InnolaTransactionServiceTests.TransactionErrorRedactsSecrets().GetAwaiter().GetResult()),
    ("innola live detail maps metadata and downloads source", () => InnolaTransactionDetailServiceTests.LiveDetailMapsTaskMetadataAndDownloadsSource().GetAwaiter().GetResult()),
    ("innola live detail without source identifiers fails safely", () => InnolaTransactionDetailServiceTests.LiveDetailWithoutSourceIdentifiersFailsSafely().GetAwaiter().GetResult()),
    ("innola transaction load creates case folder and keeps parcel workflow disabled until claim", () => InnolaTransactionLoadServiceTests.SuccessfulMockLoadCreatesCaseFolderAndKeepsParcelWorkflowDisabledUntilClaim().GetAwaiter().GetResult()),
    ("innola transaction load requires logged-in session", () => InnolaTransactionLoadServiceTests.LoadWithoutLoggedInSessionFailsWithoutEnablingParcelWorkflow().GetAwaiter().GetResult()),
    ("innola transaction load requires selected transaction", () => InnolaTransactionLoadServiceTests.LoadWithoutSelectedTransactionFailsWithoutCallingDetailService().GetAwaiter().GetResult()),
    ("innola transaction load blocks detail mismatch", () => InnolaTransactionLoadServiceTests.DetailMismatchFailsSafely().GetAwaiter().GetResult()),
    ("innola transaction load blocks unsupported attachment", () => InnolaTransactionLoadServiceTests.UnsupportedAttachmentExtensionBlocksLoad().GetAwaiter().GetResult()),
    ("innola transaction load cleans partial attachment files", () => InnolaTransactionLoadServiceTests.LaterAttachmentFailureCleansPreviouslyWrittenFiles().GetAwaiter().GetResult()),
    ("innola transaction load converts adapter exception", () => InnolaTransactionLoadServiceTests.DetailAdapterExceptionReturnsRetryableNonSecretError().GetAwaiter().GetResult()),
    ("innola transaction load blocks attachment traversal", () => InnolaTransactionLoadServiceTests.AttachmentFileNameTraversalBlocksLoad().GetAwaiter().GetResult()),
    ("innola transaction load avoids duplicate attachment overwrite", () => InnolaTransactionLoadServiceTests.DuplicateAttachmentNamesDoNotOverwriteExistingFiles().GetAwaiter().GetResult()),
    ("innola transaction load reopens existing same case", () => InnolaTransactionLoadServiceTests.ExistingCaseFolderForSameTransactionReopensWithoutDuplicatingAttachments().GetAwaiter().GetResult()),
    ("innola transaction load blocks existing mismatch", () => InnolaTransactionLoadServiceTests.ExistingCaseFolderMismatchBlocksLoad().GetAwaiter().GetResult()),
    ("innola manifest remains backward compatible", InnolaTransactionLoadServiceTests.ManifestWithoutInnolaMetadataDeserializes),
    ("innola lifecycle claim records owner manifest and audit", () => InnolaTransactionLifecycleCoordinatorTests.ClaimRecordsOwnerInSessionManifestAndAudit().GetAwaiter().GetResult()),
    ("innola lifecycle ownership conflict blocks claim", () => InnolaTransactionLifecycleCoordinatorTests.OwnershipConflictBlocksClaimAndSanitizesError().GetAwaiter().GetResult()),
    ("innola lifecycle save progress does not complete", () => InnolaTransactionLifecycleCoordinatorTests.SaveProgressPersistsLifecycleAndDoesNotComplete().GetAwaiter().GetResult()),
    ("innola lifecycle cancel clears active gate", () => InnolaTransactionLifecycleCoordinatorTests.CancelClearsActiveGateAndDoesNotComplete().GetAwaiter().GetResult()),
    ("innola lifecycle complete blocked until readiness", () => InnolaTransactionLifecycleCoordinatorTests.CompleteIsBlockedUntilReadinessPasses().GetAwaiter().GetResult()),
    ("innola lifecycle complete success clears active gate", () => InnolaTransactionLifecycleCoordinatorTests.CompleteSuccessRecordsAuditAndClearsActiveGate().GetAwaiter().GetResult()),
    ("innola lifecycle failures preserve state and redact secrets", () => InnolaTransactionLifecycleCoordinatorTests.LifecycleFailuresPreserveStateAndRedactSecrets().GetAwaiter().GetResult()),
    ("innola live lifecycle start uses workflow start endpoint", () => InnolaTransactionLifecycleServiceTests.LiveLifecycleStartUsesWorkflowStartEndpoint().GetAwaiter().GetResult()),
    ("innola live lifecycle complete resolves transition", () => InnolaTransactionLifecycleServiceTests.LiveLifecycleCompleteResolvesTransitionAndCompletes().GetAwaiter().GetResult()),
    ("innola live lifecycle business failure is redacted", () => InnolaTransactionLifecycleServiceTests.LiveLifecycleBusinessFailureIsRedacted().GetAwaiter().GetResult()),
    ("transaction panel logged out does not call transaction service", () => TransactionPanelStateTests.LoggedOutPanelDoesNotCallTransactionService().GetAwaiter().GetResult()),
    ("transaction panel logged in refresh uses session query and shows rows", () => TransactionPanelStateTests.LoggedInRefreshUsesSessionQueryAndShowsRows().GetAwaiter().GetResult()),
    ("transaction panel search sort and selection update state", () => TransactionPanelStateTests.SearchSortAndSelectionUpdatePanelState().GetAwaiter().GetResult()),
    ("transaction panel load action loads transaction and keeps workflow disabled", () => TransactionPanelStateTests.LoadActionLoadsTransactionAndKeepsParcelWorkflowDisabledUntilStart().GetAwaiter().GetResult()),
    ("transaction panel start action loads and claims transaction", () => TransactionPanelStateTests.StartActionLoadsAndClaimsTransaction().GetAwaiter().GetResult()),
    ("transaction panel active transaction locks selection search sort and refresh", () => TransactionPanelStateTests.ActiveTransactionLocksSelectionSearchSortAndRefresh().GetAwaiter().GetResult()),
    ("transaction panel stop action saves progress without completing", () => TransactionPanelStateTests.StopActionSavesProgressWithoutCompleting().GetAwaiter().GetResult()),
    ("transaction panel complete suppresses completed transaction from stale refresh", () => TransactionPanelStateTests.CompleteSuccessSuppressesCompletedTransactionFromStaleRefresh().GetAwaiter().GetResult()),
    ("transaction panel failed load preserves previous loaded transaction", () => TransactionPanelStateTests.FailedLoadPreservesPreviouslyLoadedTransaction().GetAwaiter().GetResult()),
    ("transaction panel stay decision prevents active replacement", () => TransactionPanelStateTests.ActiveTransactionStayDecisionPreventsReplacement().GetAwaiter().GetResult()),
    ("transaction panel failed refresh shows retryable redacted error and preserves rows", () => TransactionPanelStateTests.FailedRefreshShowsRetryableRedactedErrorAndPreservesRows().GetAwaiter().GetResult()),
    ("transaction panel loading refresh disables list controls", () => TransactionPanelStateTests.LoadingRefreshDisablesListControls().GetAwaiter().GetResult()),
    ("transaction panel logout clears selected transaction and rows", () => TransactionPanelStateTests.LogoutClearsSelectedTransactionRowsAndKeepsParcelWorkflowDisabled().GetAwaiter().GetResult())
};

foreach (var test in tests)
{
    test.Run();
    Console.WriteLine($"PASS {test.Name}");
}

Console.WriteLine($"PASS {tests.Length} tests");
