using ParcelWorkflowAddIn.Tests.CaseFolders;
using ParcelWorkflowAddIn.Tests.Innola;
using ParcelWorkflowAddIn.Tests.Intake;
using ParcelWorkflowAddIn.Tests.Preflight;
using ParcelWorkflowAddIn.Tests.Settings;
using ParcelWorkflowAddIn.Tests.Workflow;
using ParcelWorkflowAddIn.Tests.WorkflowRules;

var tests = new (string Name, Action Run)[]
{
    ("case folder creation creates required layout and manifest", CaseFolderStoreTests.CreateCaseCreatesLayoutAndManifest),
    ("case folder creation accepts innola transaction number", CaseFolderStoreTests.CreateCaseAcceptsInnolaTransactionNumber),
    ("case folder creation accepts live innola numeric transaction number", CaseFolderStoreTests.CreateCaseAcceptsLiveInnolaNumericTransactionNumber),
    ("case folder creation rejects duplicates", CaseFolderStoreTests.CreateCaseRejectsDuplicateTransactionFolder),
    ("case folder creation rejects unsafe transaction ids", CaseFolderStoreTests.CreateCaseRejectsUnsafeTransactionIds),
    ("case folder creation returns failure for invalid output root", CaseFolderStoreTests.CreateCaseReturnsFailureForInvalidOutputRoot),
    ("case folder reopen loads manifest state and artifacts", CaseFolderStoreTests.ReopenCaseFolderLoadsManifestStateAndArtifacts),
    ("case folder reopen reports missing manifest", CaseFolderStoreTests.ReopenCaseFolderReportsMissingManifest),
    ("case folder reopen reports corrupt manifest", CaseFolderStoreTests.ReopenCaseFolderReportsCorruptManifest),
    ("case folder reopen reports missing copied source files", CaseFolderStoreTests.ReopenCaseFolderReportsMissingCopiedSourceFiles),
    ("case folder reopen reports unknown workflow state", CaseFolderStoreTests.ReopenCaseFolderReportsUnknownWorkflowState),
    ("case folder reopen supports review approved state", CaseFolderStoreTests.ReopenCaseFolderSupportsReviewApprovedState),
    ("case folder reopen supports manual review pending state", CaseFolderStoreTests.ReopenCaseFolderSupportsManualReviewPendingState),
    ("case folder reopen supports validation states", CaseFolderStoreTests.ReopenCaseFolderSupportsValidationStates),
    ("case folder reopen supports output states", CaseFolderStoreTests.ReopenCaseFolderSupportsOutputStates),
    ("source file copy copies accepted files and updates manifest", SourceFileCopyServiceTests.CopySourceFilesCopiesAcceptedFilesAndUpdatesManifest),
    ("source file copy rejects unsupported extensions", SourceFileCopyServiceTests.CopySourceFilesRejectsUnsupportedExtensions),
    ("source file copy does not overwrite duplicate filenames", SourceFileCopyServiceTests.CopySourceFilesDoesNotOverwriteDuplicateFileNames),
    ("source file action opens copied path", SourceFileActionServiceTests.OpenUsesCopiedCaseFolderPath),
    ("source file action reveals copied path", SourceFileActionServiceTests.RevealUsesCopiedCaseFolderPath),
    ("source file action missing file returns non-blocking failure", SourceFileActionServiceTests.MissingCopiedFileReturnsNonBlockingFailure),
    ("source file action blocks tampered paths", SourceFileActionServiceTests.TamperedCopiedPathOutsideSourceDirectoryIsBlocked),
    ("source file action reports map route unavailable", SourceFileActionServiceTests.DwgTifAndTiffAreMapRouteCandidatesWithUnavailableStatus),
    ("source file action audit requires identity", SourceFileActionServiceTests.AuditIsWrittenOnlyWhenOperatorIdentityIsAvailable),
    ("source input profile detects scenario a", SourceInputProfileDetectorTests.DetectsScenarioAFromComputationAndPlanRoles),
    ("source input profile detects scenario b", SourceInputProfileDetectorTests.DetectsScenarioBFromPointsDwgAndPlanRoles),
    ("source input profile detects incomplete intake", SourceInputProfileDetectorTests.DetectsIncompleteIntakeWithMissingRoles),
    ("source input profile infers txt csv as points computation", SourceInputProfileDetectorTests.InfersTxtCsvAsPointsComputationWhenComputationAndPlanExist),
    ("source input profile infers live two pdf filenames", SourceInputProfileDetectorTests.InfersLiveTwoPdfComputationAndPlanFilenames),
    ("source input profile detects unsupported intake", SourceInputProfileDetectorTests.DetectsUnsupportedIntakeWithoutClaimingScenario),
    ("source input profile treats dwg only as incomplete", SourceInputProfileDetectorTests.DwgOnlyIntakeIsIncompleteWithScenarioBMissingRoles),
    ("source input profile labels avoid fixture case names", SourceInputProfileDetectorTests.ProductionLabelsNeverExposeFixtureCaseLabels),
    ("workflow rule resolver selects scenario a two pdf plan", WorkflowRuleResolverTests.ScenarioATwoPdfSourcesResolveToTwoPdfPlan),
    ("workflow rule resolver selects scenario b dwg aware plan", WorkflowRuleResolverTests.ScenarioBSourcesResolveToDwgAwarePlan),
    ("workflow rule resolver reports no match", WorkflowRuleResolverTests.UnknownSourceCombinationReturnsNoMatch),
    ("workflow rule resolver redacts secret parameters", WorkflowRuleResolverTests.PlanParametersDoNotPersistSecretValues),
    ("workflow rule resolver redacts configured secret values", WorkflowRuleResolverTests.PlanParametersDoNotPersistConfiguredSecretValues),
    ("manifest preflight passes valid scenario a", ManifestPreflightServiceTests.ManifestPreflightPassesValidScenarioA),
    ("manifest preflight passes valid scenario b", ManifestPreflightServiceTests.ManifestPreflightPassesValidScenarioB),
    ("structure check excludes dimension rules", ManifestPreflightServiceTests.StructureCheckExcludesDimensionRules),
    ("georeference check persists independent summary", ManifestPreflightServiceTests.GeoreferenceCheckPersistsIndependentSummary),
    ("dimension check excludes structure rules", ManifestPreflightServiceTests.DimensionCheckExcludesStructureRules),
    ("manifest preflight blocks empty dwg", ManifestPreflightServiceTests.ManifestPreflightBlocksEmptyDwg),
    ("manifest preflight blocks malformed dwg", ManifestPreflightServiceTests.ManifestPreflightBlocksMalformedDwg),
    ("manifest preflight blocks dwg with no readable sub-layers", ManifestPreflightServiceTests.ManifestPreflightBlocksDwgWithoutReadableSublayers),
    ("manifest preflight disabled dwg probe records disabled warning", ManifestPreflightServiceTests.ManifestPreflightDisabledDwgProbeRecordsDisabledWarning),
    ("manifest preflight blocks missing required dwg cad layer", ManifestPreflightServiceTests.ManifestPreflightBlocksMissingRequiredDwgCadLayer),
    ("manifest preflight disabled dwg layer rule records skipped", ManifestPreflightServiceTests.ManifestPreflightDisabledDwgLayerRuleRecordsSkipped),
    ("manifest preflight blocks missing detected profile", ManifestPreflightServiceTests.ManifestPreflightBlocksMissingDetectedProfile),
    ("manifest preflight blocks missing required role", ManifestPreflightServiceTests.ManifestPreflightBlocksMissingRequiredRole),
    ("manifest preflight blocks missing copied file", ManifestPreflightServiceTests.ManifestPreflightBlocksMissingCopiedFile),
    ("manifest preflight blocks unsupported extension", ManifestPreflightServiceTests.ManifestPreflightBlocksUnsupportedExtension),
    ("manifest preflight blocks tampered copied path", ManifestPreflightServiceTests.ManifestPreflightBlocksTamperedCopiedPath),
    ("manifest preflight summary uses snake case groups", ManifestPreflightServiceTests.ManifestPreflightSummaryUsesSnakeCaseGroups),
    ("manifest preflight hash ignores workflow state", ManifestPreflightServiceTests.ManifestPreflightHashIgnoresWorkflowState),
    ("manifest preflight blocks innola transaction without script plan", ManifestPreflightServiceTests.ManifestPreflightBlocksInnolaTransactionWithoutScriptPlan),
    ("manifest preflight blocks stale script plan", ManifestPreflightServiceTests.ManifestPreflightBlocksStaleScriptPlan),
    ("manifest preflight passes current script plan", ManifestPreflightServiceTests.ManifestPreflightPassesCurrentScriptPlan),
    ("environment preflight contributes passed checks to summary", ProcessingEnvironmentPreflightServiceTests.EnvironmentProbeContributesPassedChecksToSummary),
    ("environment preflight missing python executable blocks", ProcessingEnvironmentPreflightServiceTests.MissingPythonExecutableCreatesBlocker),
    ("environment preflight accepts sidwell python path from fake probe", ProcessingEnvironmentPreflightServiceTests.SidwellPythonPathIsAcceptedWhenFakeProbeReportsAvailable),
    ("environment preflight missing arcpy blocks", ProcessingEnvironmentPreflightServiceTests.MissingArcPyIsRequiredBlocker),
    ("environment preflight optional package missing warns", ProcessingEnvironmentPreflightServiceTests.OptionalPackageMissingIsWarning),
    ("environment preflight disabled package probe records disabled check", ProcessingEnvironmentPreflightServiceTests.DisabledPackageProbeRecordsDisabledCheck),
    ("environment preflight arcgis pro 3.7 compatible with 3.6 lane", ProcessingEnvironmentPreflightServiceTests.ArcGisPro37IsCompatibleWithConfigured36Lane),
    ("environment preflight arcgis pro assembly 13.6 compatible with 3.6 lane", ProcessingEnvironmentPreflightServiceTests.ArcGisProAssembly136IsCompatibleWithConfigured36Lane),
    ("environment preflight arcgis pro 3.5 incompatible with 3.6 lane", ProcessingEnvironmentPreflightServiceTests.ArcGisPro35IsNotCompatibleWithConfigured36Lane),
    ("environment preflight python timeout is sanitized", ProcessingEnvironmentPreflightServiceTests.PythonTimeoutIsSanitizedBlocker),
    ("environment preflight unknown arcgis version rule can escalate to blocker", ProcessingEnvironmentPreflightServiceTests.UnknownArcGisVersionRuleCanEscalateToBlocker),
    ("environment preflight async prevents duplicate run", ProcessingEnvironmentPreflightServiceTests.WorkflowSessionAsyncPreflightPreventsDuplicateRun),
    ("environment preflight reopen shows environment checks", ProcessingEnvironmentPreflightServiceTests.ReopenShowsEnvironmentChecks),
    ("environment preflight does not create downstream artifacts", ProcessingEnvironmentPreflightServiceTests.EnvironmentPreflightDoesNotCreateDownstreamArtifacts),
    ("preflight rule catalog full file is authoritative for metadata", PreflightRuleCatalogLoaderTests.FullCatalogFileIsAuthoritativeForMetadata),
    ("preflight rule catalog prefers structure rules path", PreflightRuleCatalogLoaderTests.PreferredStructureRulesPathWinsWhenPresent),
    ("preflight rule catalog falls back to legacy preflight rules path", PreflightRuleCatalogLoaderTests.LegacyPreflightRulesPathLoadsWhenStructureRulesMissing),
    ("preflight rule catalog partially invalid file falls back with warning", PreflightRuleCatalogLoaderTests.PartiallyInvalidCatalogFallsBackWithWarning),
    ("document type catalog v2 weighted match prefers specific computation sheet", DocumentTypeCatalogLoaderTests.V2CatalogLoadsAndWeightedMatchPrefersSpecificComputationSheet),
    ("document type catalog legacy compatibility adds structured points fallback", DocumentTypeCatalogLoaderTests.LegacyCatalogLoadsThroughCompatibilityAndAddsStructuredPointsFallback),
    ("document type catalog invalid v2 falls back with warning", DocumentTypeCatalogLoaderTests.PartiallyInvalidV2CatalogFallsBackWithWarning),
    ("workflow execution settings defaults to normal timeout when config missing", WorkflowExecutionSettingsTests.WorkflowExecutionSettingsDefaultsToNormalTimeoutWhenConfigMissing),
    ("workflow execution settings uses parcel fabric timeout when mode requires it", WorkflowExecutionSettingsTests.WorkflowExecutionSettingsUsesParcelFabricTimeoutWhenModeRequiresIt),
    ("workflow execution settings uses parcel fabric timeout when enterprise parcel fabric mode requires it", WorkflowExecutionSettingsTests.WorkflowExecutionSettingsUsesParcelFabricTimeoutWhenEnterpriseParcelFabricModeRequiresIt),
    ("workflow execution settings honors explicit output timeout override", WorkflowExecutionSettingsTests.WorkflowExecutionSettingsHonorsExplicitOutputTimeoutOverride),
    ("workflow execution settings loads optional non-fabric cogo toggles", WorkflowExecutionSettingsTests.WorkflowExecutionSettingsLoadsOptionalNonFabricCogoToggles),
    ("workflow state display names use compute workflow vocabulary", WorkflowStateExtensionsTests.DisplayNamesUseComputeWorkflowVocabulary),
    ("workflow session starts at no_case", WorkflowSessionTests.WorkflowSessionStartsAtNoCase),
    ("workflow session exposes intake state after creation", WorkflowSessionTests.WorkflowSessionExposesIntakeStateAfterCreation),
    ("workflow session exposes validation failure status", WorkflowSessionTests.WorkflowSessionExposesValidationFailureStatus),
    ("workflow session reset clears loaded case state", WorkflowSessionTests.WorkflowSessionResetClearsLoadedCaseState),
    ("workflow session rejects source files without active case", WorkflowSessionTests.WorkflowSessionRejectsSourceFilesWithoutActiveCase),
    ("workflow session adds source files during intake", WorkflowSessionTests.WorkflowSessionAddsSourceFilesDuringIntake),
    ("workflow session exposes rejected source file rows", WorkflowSessionTests.WorkflowSessionExposesRejectedSourceFileRows),
    ("workflow session persists detected profile without removing source files", WorkflowSessionTests.WorkflowSessionPersistsDetectedProfileWithoutRemovingSourceFiles),
    ("workflow session refresh input profile resolves innola workflow rule", WorkflowSessionTests.WorkflowSessionRefreshInputProfileResolvesInnolaWorkflowRule),
    ("workflow session reopens valid case folder", WorkflowSessionTests.WorkflowSessionReopensValidCaseFolder),
    ("workflow session reopens case with missing detected profile issue", WorkflowSessionTests.WorkflowSessionReopensCaseWithMissingDetectedProfileIssue),
    ("workflow session allows source actions after review approved", WorkflowSessionTests.WorkflowSessionAllowsSourceActionsAfterReviewApproved),
    ("workflow session review approved does not allow draft extraction rerun", WorkflowSessionTests.WorkflowSessionReviewApprovedDoesNotAllowDraftExtractionRerun),
    ("workflow session manual cogo fallback requires extracted review artifact", WorkflowSessionTests.WorkflowSessionManualCogoFallbackRequiresExtractedReviewArtifact),
    ("workflow session manual review enabled after configured weak attempt threshold", WorkflowSessionTests.WorkflowSessionManualReviewCanBeChosenAfterConfiguredWeakAttemptThresholdWithoutReviewArtifact),
    ("workflow session manual cogo fallback sets manual state and blocks validation", WorkflowSessionTests.WorkflowSessionManualCogoFallbackSetsManualStateAndBlocksValidation),
    ("workflow session reports reopen failures without replacing active case", WorkflowSessionTests.WorkflowSessionReportsReopenFailuresWithoutReplacingActiveCase),
    ("workflow session does not create processing artifacts during reopen", WorkflowSessionTests.WorkflowSessionDoesNotCreateProcessingArtifactsDuringReopen),
    ("workflow session clears reopened case state when creating new case", WorkflowSessionTests.WorkflowSessionClearsReopenedCaseStateWhenCreatingNewCase),
    ("workflow session source actions work after reopen", WorkflowSessionTests.WorkflowSessionSourceActionsWorkAfterReopen),
    ("workflow session source action failures are non-blocking", WorkflowSessionTests.WorkflowSessionSourceActionFailuresAreNonBlocking),
    ("workflow session source actions audit and avoid processing artifacts", WorkflowSessionTests.WorkflowSessionSourceActionsAuditAndAvoidProcessingArtifacts),
    ("workflow session source action succeeds when existing audit is corrupt", WorkflowSessionTests.WorkflowSessionSourceActionSucceedsWhenExistingAuditIsCorrupt),
    ("workflow session run manifest preflight blocks missing role", WorkflowSessionTests.WorkflowSessionRunManifestPreflightBlocksMissingRole),
    ("workflow session run manifest preflight can pass manifest layer", WorkflowSessionTests.WorkflowSessionRunManifestPreflightCanPassManifestLayer),
    ("workflow session structure check passes before dimension check", WorkflowSessionTests.WorkflowSessionStructureCheckPassesBeforeDimensionCheck),
    ("workflow session georeference check requires structure pass", WorkflowSessionTests.WorkflowSessionGeoreferenceCheckRequiresStructurePass),
    ("workflow session dimension check requires georeference pass", WorkflowSessionTests.WorkflowSessionDimensionCheckRequiresGeoreferencePass),
    ("workflow session dimension check requires structure pass", WorkflowSessionTests.WorkflowSessionDimensionCheckRequiresStructurePass),
    ("workflow session validate points requires both split checks", WorkflowSessionTests.WorkflowSessionValidatePointsRequiresBothSplitChecks),
    ("workflow session split summaries reopen independently", WorkflowSessionTests.WorkflowSessionSplitSummariesReopenIndependently),
    ("workflow session legacy preflight summary reopens safely", WorkflowSessionTests.WorkflowSessionLegacyPreflightSummaryReopensSafely),
    ("workflow session legacy split dimension summary migrates georeference rows safely", WorkflowSessionTests.WorkflowSessionLegacySplitDimensionSummaryMigratesGeoreferenceRowsSafely),
    ("disabled preflight result is neutral not warning", WorkflowSessionTests.DisabledPreflightResultIsNeutralNotWarning),
    ("workflow session disabled stage rows do not unlock validate points", WorkflowSessionTests.WorkflowSessionDisabledStageRowsDoNotUnlockValidatePoints),
    ("workflow session draft extraction creates review artifact", WorkflowSessionTests.WorkflowSessionDraftExtractionCreatesReviewArtifact),
    ("workflow session draft extraction failure stays contained", WorkflowSessionTests.WorkflowSessionDraftExtractionFailureStaysContained),
    ("workflow session draft extraction requires preflight pass", WorkflowSessionTests.WorkflowSessionDraftExtractionRequiresPreflightPass),
    ("draft extraction adapter matches document type catalog and enriches review artifact", CreateParcelDraftExtractionAdapterTests.ExtractionAdapterWritesMatchedDocTypeIntoReviewArtifactAndIni),
    ("draft extraction adapter keeps computation sheet primary when structured points import is enabled", CreateParcelDraftExtractionAdapterTests.ExtractionAdapterKeepsComputationSheetPrimaryWhenStructuredPointsImportIsEnabled),
    ("draft extraction adapter does not promote structured points when import is disabled", CreateParcelDraftExtractionAdapterTests.ExtractionAdapterDoesNotPromoteStructuredPointsWhenImportIsDisabled),
    ("draft extraction adapter records ai fallback when ai is disabled", CreateParcelDraftExtractionAdapterTests.ExtractionAdapterRecordsAiFallbackWhenAiIsDisabled),
    ("draft extraction adapter preserves grouping fields for grouped geometry modes", CreateParcelDraftExtractionAdapterTests.ExtractionAdapterPreservesGroupingFieldsForGroupedGeometryModes),
    ("draft extraction adapter blocks unsupported low confidence automation and writes route diagnostics", CreateParcelDraftExtractionAdapterTests.ExtractionAdapterBlocksUnsupportedLowConfidenceAutomationAndWritesRouteDiagnostics),
    ("draft extraction adapter uses text first structured pdf route when embedded text succeeds", CreateParcelDraftExtractionAdapterTests.ExtractionAdapterUsesTextFirstStructuredPdfWhenConfiguredAndTextProbeSucceeds),
    ("draft extraction adapter falls back from text first route when no usable text layer exists", CreateParcelDraftExtractionAdapterTests.ExtractionAdapterFallsBackFromTextFirstWhenNoUsableTextLayerExists),
    ("draft extraction adapter legacy catalog uses deterministic text route metadata on success", CreateParcelDraftExtractionAdapterTests.ExtractionAdapterLegacyCatalogUsesDeterministicTextRouteMetadataOnSuccess),
    ("workflow session adding source after preflight invalidates preflight", WorkflowSessionTests.WorkflowSessionAddingSourceAfterPreflightInvalidatesPreflight),
    ("workflow session refreshing profile after preflight invalidates preflight", WorkflowSessionTests.WorkflowSessionRefreshingProfileAfterPreflightInvalidatesPreflight),
    ("workflow session run manifest preflight handles corrupt manifest", WorkflowSessionTests.WorkflowSessionRunManifestPreflightHandlesCorruptManifest),
    ("workflow session reopens preflight artifact without downstream commands", WorkflowSessionTests.WorkflowSessionReopensPreflightArtifactWithoutDownstreamCommands)
    ,
    ("workflow session validation pass writes summary and state", WorkflowSessionTests.WorkflowSessionValidationPassWritesSummaryAndState),
    ("workflow session validation blocked moves workflow to blocked state", WorkflowSessionTests.WorkflowSessionValidationBlockedMovesWorkflowToBlockedState),
    ("workflow session validation exception becomes blocked failure", WorkflowSessionTests.WorkflowSessionValidationExceptionBecomesBlockedFailure),
    ("workflow session validation rejects stale approval and returns to review", WorkflowSessionTests.WorkflowSessionValidationRejectsStaleApprovalAndReturnsToReview),
    ("workflow session reopen restores validation state and artifact", WorkflowSessionTests.WorkflowSessionReopenRestoresValidationStateAndArtifact),
    ("workflow session output generation creates artifacts and advances state", WorkflowSessionTests.WorkflowSessionOutputGenerationCreatesArtifactsAndAdvancesState),
    ("workflow session enterprise publish writes summary and replaces transaction scope", WorkflowSessionTests.WorkflowSessionEnterprisePublishWritesSummaryAndReplacesTransactionScope),
    ("workflow session enterprise publish detects failed delete results", WorkflowSessionTests.WorkflowSessionEnterprisePublishDetectsFailedDeleteResults),
    ("workflow session enterprise disposition detects failed update results", WorkflowSessionTests.WorkflowSessionEnterpriseDispositionDetectsFailedUpdateResults),
    ("workflow session enterprise disposition blocks missing schema fields", WorkflowSessionTests.WorkflowSessionEnterpriseDispositionBlocksMissingSchemaFields),
    ("workflow session enterprise disposition uses ArcGIS date for feature service updates", WorkflowSessionTests.WorkflowSessionEnterpriseDispositionUsesArcGisDateForFeatureServiceUpdates),
    ("workflow session enterprise case index records spatial unit reference", () => WorkflowSessionTests.WorkflowSessionEnterpriseCaseIndexRecordsSpatialUnitReference().GetAwaiter().GetResult()),
    ("workflow session enterprise polygons record spatial unit suid in SUID field", () => WorkflowSessionTests.WorkflowSessionEnterprisePolygonsRecordSpatialUnitSuidInSuidField().GetAwaiter().GetResult()),
    ("workflow session enterprise publish filters point attributes to enterprise schema", WorkflowSessionTests.WorkflowSessionEnterprisePublishFiltersPointAttributesToEnterpriseSchema),
    ("workflow session enterprise publish reports ArcGIS add feature row errors", WorkflowSessionTests.WorkflowSessionEnterprisePublishReportsArcGisAddFeatureRowErrors),
    ("workflow session enterprise publish rejects mismatched layer target", WorkflowSessionTests.WorkflowSessionEnterprisePublishRejectsMismatchedLayerTarget),
    ("workflow session enterprise publish requires case index target", WorkflowSessionTests.WorkflowSessionEnterprisePublishRequiresCaseIndexTarget),
    ("workflow session enterprise publish failure keeps local outputs", WorkflowSessionTests.WorkflowSessionEnterprisePublishFailureKeepsLocalOutputs),
    ("workflow session records approved compute disposition artifact", WorkflowSessionTests.WorkflowSessionRecordsApprovedComputeDispositionArtifact),
    ("workflow session reopen restores compute disposition artifacts", WorkflowSessionTests.WorkflowSessionReopenRestoresComputeDispositionArtifacts),
    ("workflow session regenerating outputs invalidates compute disposition", WorkflowSessionTests.WorkflowSessionRegeneratingOutputsInvalidatesComputeDisposition),
    ("workflow session disposition writeback updates scoped enterprise rows", WorkflowSessionTests.WorkflowSessionDispositionWritebackUpdatesScopedEnterpriseRows),
    ("workflow session enterprise parcel fabric publishes during outputs when configured", WorkflowSessionTests.WorkflowSessionEnterpriseParcelFabricPublishesDuringOutputsWhenConfigured),
    ("workflow session output generation requires validation pass", WorkflowSessionTests.WorkflowSessionOutputGenerationRequiresValidationPass),
    ("workflow session output failure returns to validation passed", WorkflowSessionTests.WorkflowSessionOutputFailureReturnsToValidationPassed),
    ("workflow session reopen restores output state and artifact", WorkflowSessionTests.WorkflowSessionReopenRestoresSpatialReviewPendingStateAndArtifacts),
    ("workflow session reopen detects enterprise working state alongside local artifacts", WorkflowSessionTests.WorkflowSessionReopenDetectsEnterpriseWorkingStateAlongsideLocalArtifacts),
    ("workflow session reopen hydrates output summary from enterprise working state when local output summary is missing", WorkflowSessionTests.WorkflowSessionReopenHydratesOutputSummaryFromEnterpriseWorkingStateWhenLocalOutputSummaryIsMissing),
    ("workflow session reopen reports partial enterprise restore warnings", WorkflowSessionTests.WorkflowSessionReopenReportsPartialEnterpriseRestoreWarnings),
    ("workflow session spatial review approval unlocks ready-to-complete", WorkflowSessionTests.WorkflowSessionSpatialReviewApprovalUnlocksReadyToComplete),
    ("workflow session reopen invalidates stale spatial review approval", WorkflowSessionTests.WorkflowSessionReopenInvalidatesStaleSpatialReviewApproval)
    ,
    ("preflight rule catalog missing file falls back to safe defaults", PreflightRuleCatalogLoaderTests.MissingRulesFileFallsBackToSafeDefaults),
    ("workspace planner resolves intake stage focus", WorkflowWorkspacePlannerTests.IntakeStatesResolveToIntakeWorkspace),
    ("workspace planner advances completed intake to preflight focus", WorkflowWorkspacePlannerTests.IntakeReadyForPreflightResolvesToPreflightWorkspace),
    ("workspace planner resolves preflight stage focus", WorkflowWorkspacePlannerTests.PreflightStatesResolveToPreflightWorkspace),
    ("workspace planner resolves extraction stage focus", WorkflowWorkspacePlannerTests.ReviewStatesResolveToExtractionWorkspace),
    ("workspace planner resolves validation stage focus", WorkflowWorkspacePlannerTests.ValidationStatesResolveToValidationWorkspace),
    ("workspace planner resolves outputs stage focus", WorkflowWorkspacePlannerTests.ValidationPassedResolvesToOutputsWorkspace),
    ("workspace planner resolves spatial review focus", WorkflowWorkspacePlannerTests.OutputCreatedResolvesToSpatialReviewWorkspace),
    ("workspace planner resolves ready-to-complete focus", WorkflowWorkspacePlannerTests.SpatialReviewApprovedResolvesToReadyToCompleteWorkspace),
    ("output map review styling places parcel fabric below review overlays", OutputMapReviewStylingTests.OrderLayerPathsPlacesParcelFabricBelowReviewOverlays),
    ("output map review styling orders polygons lines and points", OutputMapReviewStylingTests.OrderLayerPathsPlacesPolygonsBelowLinesBelowPoints),
    ("output map review styling uses non-fabric review messaging", OutputMapReviewStylingTests.BuildSuccessMessageUsesNonFabricReviewLanguage),
    ("output map review styling builds transaction review group layer name", OutputMapReviewStylingTests.BuildTransactionGroupLayerNameUsesTransactionNumber),
    ("output map review styling routes supporting layers to hidden subgroup", OutputMapReviewStylingTests.SupportingLayerPathsRouteToSupportingSourcesAndHideByDefault),
    ("output map review styling prefers root feature class diagnostics", OutputMapReviewStylingTests.BuildSuccessMessagePrefersRootFeatureClassDiagnosticsWhenAvailable),
    ("output summary persistence returns parcel fabric layer plus review overlays", OutputMapReviewStylingTests.ParcelFabricModeReturnsFabricLayerPlusReviewOverlays),
    ("output summary persistence preserves parcel fabric supporting layers", OutputMapReviewStylingTests.ParcelFabricModePreservesSupportingSurveyAndCadLayers),
    ("output summary persistence returns enterprise parcel fabric targets plus overlays", OutputMapReviewStylingTests.EnterpriseParcelFabricModeReturnsPublishedFabricTargetsPlusOverlays),
    ("output summary persistence returns enterprise working layer targets", OutputMapReviewStylingTests.EnterpriseWorkingLayersModeReturnsTransactionScopedWorkingTargets),
    ("output summary persistence keeps local enterprise working outputs loadable without publish evidence", OutputMapReviewStylingTests.EnterpriseWorkingLayersModeFallsBackToLocalOutputsWhenPublishEvidenceIsMissing),
    ("output map review styling uses enterprise parcel fabric review messaging", OutputMapReviewStylingTests.BuildSuccessMessageUsesEnterpriseParcelFabricLanguage),
    ("review source resolver prefers computation first", ReviewSourceSelectionResolverTests.ResolverPrefersComputationThenPointsThenPlan),
    ("review source resolver keeps explicit selection", ReviewSourceSelectionResolverTests.ResolverKeepsExplicitSelectionWhenAvailable),
    ("review source resolver falls back when explicit selection disappears", ReviewSourceSelectionResolverTests.ResolverFallsBackWhenExplicitSelectionDisappears),
    ("review source viewer projects pdf support", ReviewSourceViewerStateProjectorTests.ProjectorSupportsPdfSources),
    ("review source viewer projects image support", ReviewSourceViewerStateProjectorTests.ProjectorSupportsRasterAndImageSources),
    ("review source viewer falls back for unsupported files", ReviewSourceViewerStateProjectorTests.ProjectorFallsBackWhenSourceIsUnsupported),
    ("review source viewer falls back for missing files", ReviewSourceViewerStateProjectorTests.ProjectorFallsBackWhenSourceFileIsMissing),
    ("review source viewer surfaces render failure fallback", ReviewSourceViewerStateProjectorTests.ProjectorCanSurfaceRenderFailureFallback),
    ("points validation workspace close status uses discard message", PointsValidationWorkspaceMessagesTests.CloseStatusUsesDiscardMessageWhenUnsavedChangesAreDropped),
    ("points validation workspace close status uses create spatial units readiness message", PointsValidationWorkspaceMessagesTests.CloseStatusUsesCreateSpatialUnitsReadinessWhenContinueWasConfirmed),
    ("points validation workspace close status uses saved only message", PointsValidationWorkspaceMessagesTests.CloseStatusUsesSavedOnlyMessageWhenPointsWereSavedButNotContinued),
    ("parcel scoped manual point uses active parcel context", ParcelScopedManualPointServiceTests.CreateManualRowUsesActiveParcelContextAndNextSequence),
    ("parcel scoped manual point inserts after selected sequence", ParcelScopedManualPointServiceTests.CreateManualRowInsertsAfterSelectedSequenceAndShiftsLaterRows),
    ("point edit draft validates required and numeric fields", PointEditDraftTests.ValidateRejectsMissingAndInvalidNumericFields),
    ("point edit draft blocks duplicate point id within parcel", PointEditDraftTests.ValidateBlocksDuplicatePointIdWithinParcel),
    ("point edit draft applies values to row model", PointEditDraftTests.ApplyToWritesCommittedValuesToRow),
    ("parcel scoped review validation blocks duplicate point ids", ParcelScopedReviewValidationServiceTests.ValidateBlocksDuplicatePointIdsWithinParcel),
    ("parcel scoped review validation blocks pending manual edit and invalid coordinates", ParcelScopedReviewValidationServiceTests.ValidateBlocksPendingManualEditAndInvalidCoordinates),
    ("parcel scoped review validation blocks missing parcel assignment and invalid sequence", ParcelScopedReviewValidationServiceTests.ValidateBlocksManualRowsWithoutParcelAssignmentOrValidSequence),
    ("parcel scoped review validation allows implicit closure for structured traverse rows", ParcelScopedReviewValidationServiceTests.ValidateAllowsImplicitClosureForStructuredTraverseRows),
    ("review persistence saves edited row and preserves originals", ExtractionReviewPersistenceServiceTests.LoadEditAndSaveReviewArtifactPersistsOverrides),
    ("review persistence saves manual row", ExtractionReviewPersistenceServiceTests.ManualPointSavePersistsAsManualRow),
    ("review approval blocks unresolved rows", ExtractionReviewPersistenceServiceTests.ApprovalIsBlockedWhenUnresolvedRowsRemain),
    ("review approval writes hash and later edits invalidate it", ExtractionReviewPersistenceServiceTests.ApprovalWritesHashAndIsInvalidatedByLaterEdit),
    ("innola session starts logged out with safe gates", InnolaSessionManagerTests.SessionStartsLoggedOutWithSafeGates),
    ("innola successful login stores session in memory and enables transactions", () => InnolaSessionManagerTests.SuccessfulLoginStoresSessionInMemoryAndEnablesTransactions().GetAwaiter().GetResult()),
    ("innola failed login does not create session and keeps non-secret error", () => InnolaSessionManagerTests.FailedLoginDoesNotCreateSessionAndKeepsNonSecretError().GetAwaiter().GetResult()),
    ("innola timed-out login returns to logged out and re-enables login", () => InnolaSessionManagerTests.TimedOutLoginReturnsToLoggedOutAndReEnablesLogin().GetAwaiter().GetResult()),
    ("innola logout clears session secrets and disables gates", () => InnolaSessionManagerTests.LogoutClearsSessionSecretsAndDisablesGates().GetAwaiter().GetResult()),
    ("innola session expiry clears session secrets and disables gates", InnolaSessionManagerTests.SessionExpiryClearsSessionSecretsAndDisablesGates),
    ("innola session secrets are not written to settings or case folder files", () => InnolaSessionManagerTests.SessionSecretsAreNotWrittenToSettingsOrCaseFolderFiles().GetAwaiter().GetResult()),
    ("innola auth maps user and group context from response", () => InnolaAuthServiceTests.LoginMapsUserAndGroupContextFromResponse().GetAwaiter().GetResult()),
    ("innola session manager raises login change on caller context", () => InnolaAuthServiceTests.SessionManagerRaisesLoginChangeOnCallerContext().GetAwaiter().GetResult()),
    ("innola mock auth enables dry run login", () => InnolaAuthServiceTests.MockAuthEnablesDryRunLogin().GetAwaiter().GetResult()),
    ("innola certificate settings map from workflow settings", InnolaTransactionSettingsTests.CertificateSettingsMapFromWorkflowSettings),
    ("innola supported transaction types load from configuration", InnolaTransactionSettingsTests.SupportedTransactionTypesLoadFromConfiguration),
    ("innola missing supported transaction types fall back to safe defaults", InnolaTransactionSettingsTests.MissingSupportedTransactionTypesFallBackToSafeDefaults),
    ("innola invalid supported transaction types fall back to safe defaults", InnolaTransactionSettingsTests.InvalidSupportedTransactionTypesFallBackToSafeDefaults),
    ("innola compute workflow stages load from configuration", InnolaTransactionSettingsTests.ComputeWorkflowStagesLoadFromConfiguration),
    ("innola manual review retry threshold loads from configuration", InnolaTransactionSettingsTests.ManualReviewRetryThresholdLoadsFromConfiguration),
    ("innola invalid review workspace mode falls back to normal", InnolaTransactionSettingsTests.InvalidReviewWorkspaceModeFallsBackToNormal),
    ("innola legacy parcel fabric review workspace mode normalizes to local parcel fabric", InnolaTransactionSettingsTests.LegacyParcelFabricReviewWorkspaceModeNormalizesToLocalParcelFabric),
    ("innola enterprise working layers mode loads enterprise configuration", InnolaTransactionSettingsTests.EnterpriseWorkingLayersModeLoadsEnterpriseConfiguration),
    ("innola enterprise working publish timing defaults to on complete", InnolaTransactionSettingsTests.EnterpriseWorkingPublishTimingDefaultsToOnComplete),
    ("innola enterprise parcel fabric mode loads enterprise parcel fabric configuration", InnolaTransactionSettingsTests.EnterpriseParcelFabricModeLoadsEnterpriseParcelFabricConfiguration),
    ("innola normal mode does not warn about missing enterprise targets", InnolaTransactionSettingsTests.NormalModeDoesNotWarnAboutMissingEnterpriseTargets),
    ("innola enterprise mode warns when required targets are missing", InnolaTransactionSettingsTests.EnterpriseModeWarnsWhenRequiredTargetsAreMissing),
    ("innola enterprise parcel fabric mode warns when required targets are missing", InnolaTransactionSettingsTests.EnterpriseParcelFabricModeWarnsWhenRequiredTargetsAreMissing),
    ("innola configuration summary formats supported transaction types", InnolaTransactionSettingsTests.ConfigurationSummaryFormatsSupportedTransactionTypes),
    ("innola configuration summary formats review workspace mode", InnolaTransactionSettingsTests.ConfigurationSummaryFormatsReviewWorkspaceMode),
    ("settings workspace exposes expected tabs and loads current fields", SettingsWorkspaceServiceTests.SettingsWorkspaceExposesExpectedTabsAndLoadsCurrentFields),
    ("settings workspace save round trip persists workflow and rule edits", SettingsWorkspaceServiceTests.SettingsWorkspaceSaveRoundTripPersistsWorkflowAndRuleEdits),
    ("settings workspace load and save round trip persists readiness rule overrides", SettingsWorkspaceServiceTests.SettingsWorkspaceLoadAndSaveRoundTripPersistsReadinessRuleOverrides),
    ("settings workspace validation rejects invalid readiness configuration", SettingsWorkspaceServiceTests.SettingsWorkspaceValidationRejectsInvalidReadinessConfiguration),
    ("settings workspace validation rejects invalid enterprise and secret configuration", SettingsWorkspaceServiceTests.SettingsWorkspaceValidationRejectsInvalidEnterpriseAndSecretConfiguration),
    ("settings workspace validation requires enterprise working case index layer", SettingsWorkspaceServiceTests.SettingsWorkspaceValidationRequiresEnterpriseWorkingCaseIndexLayer),
    ("settings workspace validation rejects invalid enterprise parcel fabric configuration", SettingsWorkspaceServiceTests.SettingsWorkspaceValidationRejectsInvalidEnterpriseParcelFabricConfiguration),
    ("settings workspace load surfaces enterprise parcel fabric warnings in summary", SettingsWorkspaceServiceTests.SettingsWorkspaceLoadSurfacesEnterpriseParcelFabricWarningsInSummary),
    ("innola transaction service maps prior payload and filters unavailable rows", InnolaTransactionServiceTests.MapsPriorInnolaTaskPayloadAndFiltersUnavailableRows),
    ("innola transaction service uses workflow my-tasks endpoint", () => InnolaTransactionServiceTests.HttpTransactionServiceUsesWorkflowMyTasksEndpoint().GetAwaiter().GetResult()),
    ("innola transaction service falls back to application search when workflow rows are empty", () => InnolaTransactionServiceTests.HttpTransactionServiceFallsBackToApplicationSearchWhenWorkflowRowsAreEmpty().GetAwaiter().GetResult()),
    ("innola transaction service keeps workflow result when application search fails", () => InnolaTransactionServiceTests.HttpTransactionServiceKeepsWorkflowResultWhenApplicationSearchFails().GetAwaiter().GetResult()),
    ("innola transaction service uses exact transaction number search payload", () => InnolaTransactionServiceTests.HttpTransactionServiceUsesExactTransactionNumberSearchPayload().GetAwaiter().GetResult()),
    ("innola transaction service falls back to wildcard transaction search when exact returns empty", () => InnolaTransactionServiceTests.HttpTransactionServiceFallsBackToWildcardTransactionSearchWhenExactReturnsEmpty().GetAwaiter().GetResult()),
    ("innola transaction service falls back to contains wildcard for short transaction fragments", () => InnolaTransactionServiceTests.HttpTransactionServiceFallsBackToContainsWildcardForShortTransactionFragments().GetAwaiter().GetResult()),
    ("innola mock transaction service requires session and filters rows", () => InnolaTransactionServiceTests.MockTransactionServiceRequiresSessionAndFiltersRows().GetAwaiter().GetResult()),
    ("innola transaction errors redact secrets", () => InnolaTransactionServiceTests.TransactionErrorRedactsSecrets().GetAwaiter().GetResult()),
    ("innola live detail maps metadata and downloads source", () => InnolaTransactionDetailServiceTests.LiveDetailMapsTaskMetadataAndDownloadsSource().GetAwaiter().GetResult()),
    ("innola live detail without source identifiers fails safely", () => InnolaTransactionDetailServiceTests.LiveDetailWithoutSourceIdentifiersFailsSafely().GetAwaiter().GetResult()),
    ("innola transaction load creates case folder and keeps parcel workflow disabled until claim", () => InnolaTransactionLoadServiceTests.SuccessfulMockLoadCreatesCaseFolderAndKeepsParcelWorkflowDisabledUntilClaim().GetAwaiter().GetResult()),
    ("innola transaction load requires logged-in session", () => InnolaTransactionLoadServiceTests.LoadWithoutLoggedInSessionFailsWithoutEnablingParcelWorkflow().GetAwaiter().GetResult()),
    ("innola transaction load requires selected transaction", () => InnolaTransactionLoadServiceTests.LoadWithoutSelectedTransactionFailsWithoutCallingDetailService().GetAwaiter().GetResult()),
    ("innola transaction load blocks detail mismatch", () => InnolaTransactionLoadServiceTests.DetailMismatchFailsSafely().GetAwaiter().GetResult()),
    ("innola transaction load blocks unsupported attachment", () => InnolaTransactionLoadServiceTests.UnsupportedAttachmentExtensionBlocksLoad().GetAwaiter().GetResult()),
    ("innola transaction load cleans partial attachment files", () => InnolaTransactionLoadServiceTests.LaterAttachmentFailureCleansPreviouslyWrittenFiles().GetAwaiter().GetResult()),
    ("innola transaction load converts adapter exception", () => InnolaTransactionLoadServiceTests.DetailAdapterExceptionReturnsRetryableNonSecretError().GetAwaiter().GetResult()),
    ("innola transaction load blocks attachment traversal", () => InnolaTransactionLoadServiceTests.AttachmentFileNameTraversalBlocksLoad().GetAwaiter().GetResult()),
    ("innola transaction load avoids duplicate attachment overwrite", () => InnolaTransactionLoadServiceTests.DuplicateAttachmentNamesDoNotOverwriteExistingFiles().GetAwaiter().GetResult()),
    ("innola transaction load restores resume package state", () => InnolaTransactionLoadServiceTests.ResumePackageRestoresSavedWorkflowState().GetAwaiter().GetResult()),
    ("innola resume package excludes heavy output artifacts", () => InnolaTransactionLoadServiceTests.ResumePackageExcludesHeavyOutputArtifactsButKeepsWorkingState().GetAwaiter().GetResult()),
    ("innola completed package skips file geodatabase lock files", () => InnolaTransactionLoadServiceTests.CompletedPackageSkipsFileGeodatabaseLockFiles().GetAwaiter().GetResult()),
    ("innola transaction load reopens existing same case", () => InnolaTransactionLoadServiceTests.ExistingCaseFolderForSameTransactionReopensWithoutDuplicatingAttachments().GetAwaiter().GetResult()),
    ("innola transaction load blocks existing mismatch", () => InnolaTransactionLoadServiceTests.ExistingCaseFolderMismatchBlocksLoad().GetAwaiter().GetResult()),
    ("innola transaction load persists workflow script plan", () => InnolaTransactionLoadServiceTests.SuccessfulLoadPersistsWorkflowRuleAndScriptPlan().GetAwaiter().GetResult()),
    ("innola manifest remains backward compatible", InnolaTransactionLoadServiceTests.ManifestWithoutInnolaMetadataDeserializes),
    ("innola lifecycle claim records owner manifest and audit", () => InnolaTransactionLifecycleCoordinatorTests.ClaimRecordsOwnerInSessionManifestAndAudit().GetAwaiter().GetResult()),
    ("innola lifecycle ownership conflict blocks claim", () => InnolaTransactionLifecycleCoordinatorTests.OwnershipConflictBlocksClaimAndSanitizesError().GetAwaiter().GetResult()),
    ("innola lifecycle save progress does not complete", () => InnolaTransactionLifecycleCoordinatorTests.SaveProgressPersistsLifecycleAndDoesNotComplete().GetAwaiter().GetResult()),
    ("innola lifecycle save and close uploads resume package", () => InnolaTransactionLifecycleCoordinatorTests.SaveAndCloseUploadsResumePackageAndPersistsProgress().GetAwaiter().GetResult()),
    ("innola lifecycle cancel clears active gate", () => InnolaTransactionLifecycleCoordinatorTests.CancelClearsActiveGateAndDoesNotComplete().GetAwaiter().GetResult()),
    ("innola lifecycle complete blocked until readiness", () => InnolaTransactionLifecycleCoordinatorTests.CompleteIsBlockedUntilReadinessPasses().GetAwaiter().GetResult()),
    ("innola lifecycle complete success clears active gate", () => InnolaTransactionLifecycleCoordinatorTests.CompleteSuccessRecordsAuditAndClearsActiveGate().GetAwaiter().GetResult()),
    ("innola lifecycle complete creates spatial unit before closing", () => InnolaTransactionLifecycleCoordinatorTests.CompleteCreatesSpatialUnitAndPersistsReturnedIdBeforeLifecycleComplete().GetAwaiter().GetResult()),
    ("innola lifecycle complete blocks on spatial unit failure", () => InnolaTransactionLifecycleCoordinatorTests.CompleteStopsBeforePackageUploadAndLifecycleCompleteWhenSpatialUnitFails().GetAwaiter().GetResult()),
    ("innola lifecycle complete generates report before package upload", () => InnolaTransactionLifecycleCoordinatorTests.CompleteGeneratesReportBeforePackageUploadAndIncludesReportInPackage().GetAwaiter().GetResult()),
    ("innola lifecycle complete blocks on report generation failure", () => InnolaTransactionLifecycleCoordinatorTests.CompleteStopsBeforePackageUploadWhenReportGenerationFails().GetAwaiter().GetResult()),
    ("innola lifecycle complete blocks on plan check writeback failure", () => InnolaTransactionLifecycleCoordinatorTests.CompleteStopsBeforePackageUploadWhenPlanCheckWritebackFails().GetAwaiter().GetResult()),
    ("compute examination report generation uses persisted stage findings", ComputeExaminationReportServiceTests.ReportGenerationUsesPersistedStageFindings),
    ("innola lifecycle complete blocks on working package upload failure", () => InnolaTransactionLifecycleCoordinatorTests.CompleteStopsBeforeLifecycleCompleteWhenWorkingPackageUploadFails().GetAwaiter().GetResult()),
    ("innola lifecycle failures preserve state and redact secrets", () => InnolaTransactionLifecycleCoordinatorTests.LifecycleFailuresPreserveStateAndRedactSecrets().GetAwaiter().GetResult()),
    ("innola live lifecycle start uses workflow start endpoint", () => InnolaTransactionLifecycleServiceTests.LiveLifecycleStartUsesWorkflowStartEndpoint().GetAwaiter().GetResult()),
    ("innola live lifecycle complete resolves transition", () => InnolaTransactionLifecycleServiceTests.LiveLifecycleCompleteResolvesTransitionAndCompletes().GetAwaiter().GetResult()),
    ("innola live lifecycle business failure is redacted", () => InnolaTransactionLifecycleServiceTests.LiveLifecycleBusinessFailureIsRedacted().GetAwaiter().GetResult()),
    ("innola live detail falls back to transaction sources and downloads body", () => InnolaTransactionDetailServiceTests.LiveDetailFallsBackToTransactionSourcesAndDownloadsBody().GetAwaiter().GetResult()),
    ("innola live detail falls back to application id when transaction sources are empty", () => InnolaTransactionDetailServiceTests.LiveDetailFallsBackToApplicationIdWhenTransactionSourcesAreEmpty().GetAwaiter().GetResult()),
    ("innola live detail falls back to scanning application sources and downloads body", () => InnolaTransactionDetailServiceTests.LiveDetailFallsBackToScanningApplicationSourcesAndDownloadsBody().GetAwaiter().GetResult()),
    ("innola live detail keeps selected transaction number when detail only has application number", () => InnolaTransactionDetailServiceTests.LiveDetailKeepsSelectedTransactionNumberWhenDetailOnlyHasApplicationNumber().GetAwaiter().GetResult()),
    ("innola spatial unit service creates defaults then saves", () => InnolaSpatialUnitServiceTests.CreatesDefaultsThenSavesPopulatedSpatialUnit().GetAwaiter().GetResult()),
    ("innola spatial unit service blocks unauthorized session", () => InnolaSpatialUnitServiceTests.ReturnsFailureForUnauthorizedSession().GetAwaiter().GetResult()),
    ("innola plan check service writes checklist and preserves payload", () => InnolaPlanCheckServiceTests.WritesPlanChecklistAndPreservesPlanPayload().GetAwaiter().GetResult()),
    ("innola plan check service does not pass pending stages", () => InnolaPlanCheckServiceTests.DoesNotPassRowsForPendingStageStatus().GetAwaiter().GetResult()),
    ("innola plan check service fails when checklist missing", () => InnolaPlanCheckServiceTests.FailsWhenChecklistIsMissing().GetAwaiter().GetResult()),
    ("innola plan check service blocks unauthorized session", () => InnolaPlanCheckServiceTests.FailsBeforeHttpWhenUnauthorized().GetAwaiter().GetResult()),
    ("transaction panel logged out does not call transaction service", () => TransactionPanelStateTests.LoggedOutPanelDoesNotCallTransactionService().GetAwaiter().GetResult()),
    ("transaction panel logged in refresh uses session query and shows rows", () => TransactionPanelStateTests.LoggedInRefreshUsesSessionQueryAndShowsRows().GetAwaiter().GetResult()),
    ("transaction panel search remains enabled when refresh returns no rows", () => TransactionPanelStateTests.SearchRemainsEnabledWhenRefreshReturnsNoRows().GetAwaiter().GetResult()),
    ("transaction panel search sort and selection update state", () => TransactionPanelStateTests.SearchSortAndSelectionUpdatePanelState().GetAwaiter().GetResult()),
    ("transaction panel search text refreshes from server for missing transaction number", () => TransactionPanelStateTests.SearchTextRefreshesFromServerForMissingTransactionNumber().GetAwaiter().GetResult()),
    ("transaction panel load selected transaction clears stale search text", () => TransactionPanelStateTests.LoadSelectedTransactionClearsStaleSearchText().GetAwaiter().GetResult()),
    ("transaction panel load action loads transaction and keeps workflow disabled", () => TransactionPanelStateTests.LoadActionLoadsTransactionAndKeepsParcelWorkflowDisabledUntilStart().GetAwaiter().GetResult()),
    ("transaction panel unsupported transaction type blocks workflow load", () => TransactionPanelStateTests.UnsupportedTransactionTypeBlocksWorkflowLoadBeforeCaseFolderCreation().GetAwaiter().GetResult()),
    ("transaction panel unsupported workflow stage blocks compute workflow launch", () => TransactionPanelStateTests.UnsupportedWorkflowStageBlocksComputeWorkflowLaunch().GetAwaiter().GetResult()),
    ("transaction panel start action loads and claims transaction", () => TransactionPanelStateTests.StartActionLoadsAndClaimsTransaction().GetAwaiter().GetResult()),
    ("transaction panel add documents copies files into loaded transaction", () => TransactionPanelStateTests.AddDocumentsCopiesFilesIntoLoadedTransaction().GetAwaiter().GetResult()),
    ("transaction panel active transaction locks selection search sort and refresh", () => TransactionPanelStateTests.ActiveTransactionLocksSelectionSearchSortAndRefresh().GetAwaiter().GetResult()),
    ("transaction panel stop action saves progress without completing", () => TransactionPanelStateTests.StopActionSavesProgressWithoutCompleting().GetAwaiter().GetResult()),
    ("transaction panel complete suppresses completed transaction from stale refresh", () => TransactionPanelStateTests.CompleteSuccessSuppressesCompletedTransactionFromStaleRefresh().GetAwaiter().GetResult()),
    ("transaction panel workflow exit suspend restores transaction list context", () => TransactionPanelStateTests.WorkflowExitSuspendRestoresTransactionListContext().GetAwaiter().GetResult()),
    ("transaction panel workflow exit cancel restores transaction list context", () => TransactionPanelStateTests.WorkflowExitCancelRestoresTransactionListContext().GetAwaiter().GetResult()),
    ("transaction panel workflow exit complete refreshes and suppresses completed transaction", () => TransactionPanelStateTests.WorkflowExitCompleteRefreshesAndSuppressesCompletedTransaction().GetAwaiter().GetResult()),
    ("transaction panel failed load preserves previous loaded transaction", () => TransactionPanelStateTests.FailedLoadPreservesPreviouslyLoadedTransaction().GetAwaiter().GetResult()),
    ("transaction panel stay decision prevents active replacement", () => TransactionPanelStateTests.ActiveTransactionStayDecisionPreventsReplacement().GetAwaiter().GetResult()),
    ("transaction panel failed refresh shows retryable redacted error and preserves rows", () => TransactionPanelStateTests.FailedRefreshShowsRetryableRedactedErrorAndPreservesRows().GetAwaiter().GetResult()),
    ("transaction panel loading refresh disables list controls", () => TransactionPanelStateTests.LoadingRefreshDisablesListControls().GetAwaiter().GetResult()),
    ("transaction panel refresh timeout releases disabled controls", () => TransactionPanelStateTests.RefreshTimeoutReleasesDisabledControls().GetAwaiter().GetResult()),
    ("transaction panel logout clears selected transaction and rows", () => TransactionPanelStateTests.LogoutClearsSelectedTransactionRowsAndKeepsParcelWorkflowDisabled().GetAwaiter().GetResult())
};

var selectedTests = args.Length == 0
    ? tests
    : tests
        .Where(test => args.Any(arg => test.Name.Contains(arg, StringComparison.OrdinalIgnoreCase)))
        .ToArray();

foreach (var test in selectedTests)
{
    test.Run();
    Console.WriteLine($"PASS {test.Name}");
}

Console.WriteLine($"PASS {selectedTests.Length} tests");
