#pragma checksum "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\CompareWorkspaceWindow.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "0131436F9061D0DC2B56684FCBAADA865512D20A"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using ArcGIS.Desktop.Framework.Controls;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace ParcelWorkflowAddIn {
    
    
    /// <summary>
    /// CompareWorkspaceWindow
    /// </summary>
    public partial class CompareWorkspaceWindow : ArcGIS.Desktop.Framework.Controls.ProWindow, System.Windows.Markup.IComponentConnector {
        
        
        #line 39 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\CompareWorkspaceWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ColumnDefinition PdfPanelColumn;
        
        #line default
        #line hidden
        
        
        #line 40 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\CompareWorkspaceWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ColumnDefinition PdfPanelSpacerColumn;
        
        #line default
        #line hidden
        
        
        #line 44 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\CompareWorkspaceWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border PdfPanel;
        
        #line default
        #line hidden
        
        
        #line 72 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\CompareWorkspaceWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid DocumentWebViewHost;
        
        #line default
        #line hidden
        
        
        #line 73 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\CompareWorkspaceWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ScrollViewer ImageScrollViewer;
        
        #line default
        #line hidden
        
        
        #line 74 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\CompareWorkspaceWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image DocumentImage;
        
        #line default
        #line hidden
        
        
        #line 76 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\CompareWorkspaceWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock DocumentFallbackText;
        
        #line default
        #line hidden
        
        
        #line 82 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\CompareWorkspaceWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.GridSplitter PdfPanelSplitter;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.7.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/ParcelWorkflowAddIn;V1.1.310.0;component/compareworkspacewindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\CompareWorkspaceWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.7.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.PdfPanelColumn = ((System.Windows.Controls.ColumnDefinition)(target));
            return;
            case 2:
            this.PdfPanelSpacerColumn = ((System.Windows.Controls.ColumnDefinition)(target));
            return;
            case 3:
            this.PdfPanel = ((System.Windows.Controls.Border)(target));
            return;
            case 4:
            this.DocumentWebViewHost = ((System.Windows.Controls.Grid)(target));
            return;
            case 5:
            this.ImageScrollViewer = ((System.Windows.Controls.ScrollViewer)(target));
            return;
            case 6:
            this.DocumentImage = ((System.Windows.Controls.Image)(target));
            return;
            case 7:
            this.DocumentFallbackText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 8:
            this.PdfPanelSplitter = ((System.Windows.Controls.GridSplitter)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

