#pragma checksum "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "BAA695CD1615EADE2DD195B9C2786E0D78F1F5DA"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using ArcGIS.Desktop.Framework.Controls;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace ParcelWorkflowAddIn {
    
    
    /// <summary>
    /// ConfigurationWindow
    /// </summary>
    public partial class ConfigurationWindow : ArcGIS.Desktop.Framework.Controls.ProWindow, System.Windows.Markup.IComponentConnector {
        
        
        #line 23 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock SettingsSummaryText;
        
        #line default
        #line hidden
        
        
        #line 29 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabControl SettingsTabControl;
        
        #line default
        #line hidden
        
        
        #line 44 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox SettingsPathTextBox;
        
        #line default
        #line hidden
        
        
        #line 56 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox CaseFolderRootTextBox;
        
        #line default
        #line hidden
        
        
        #line 67 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox PythonExecutableTextBox;
        
        #line default
        #line hidden
        
        
        #line 82 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox OutputAdapterScriptPathTextBox;
        
        #line default
        #line hidden
        
        
        #line 93 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox ValidationAdapterScriptPathTextBox;
        
        #line default
        #line hidden
        
        
        #line 104 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox ValidationRulesPathTextBox;
        
        #line default
        #line hidden
        
        
        #line 115 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox OutputAdapterTimeoutTextBox;
        
        #line default
        #line hidden
        
        
        #line 126 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox SdkLaneSummaryTextBox;
        
        #line default
        #line hidden
        
        
        #line 156 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox OcrEngineComboBox;
        
        #line default
        #line hidden
        
        
        #line 163 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox OpenAiEnabledCheckBox;
        
        #line default
        #line hidden
        
        
        #line 174 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox OpenAiExtractionProfileComboBox;
        
        #line default
        #line hidden
        
        
        #line 190 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox OpenAiModelTextBox;
        
        #line default
        #line hidden
        
        
        #line 201 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox OpenAiApiKeyEnvironmentVariableTextBox;
        
        #line default
        #line hidden
        
        
        #line 228 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox InnolaServerUrlTextBox;
        
        #line default
        #line hidden
        
        
        #line 239 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox InnolaModeComboBox;
        
        #line default
        #line hidden
        
        
        #line 253 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox InnolaProcessStepTextBox;
        
        #line default
        #line hidden
        
        
        #line 264 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox SupportedTransactionTypesTextBox;
        
        #line default
        #line hidden
        
        
        #line 281 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox ComputeAttachmentSourceTypesTextBox;
        
        #line default
        #line hidden
        
        
        #line 299 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox ComputeTransactionTypeProfilesTextBox;
        
        #line default
        #line hidden
        
        
        #line 315 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox ComputeWorkflowStagesTextBox;
        
        #line default
        #line hidden
        
        
        #line 327 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox InnolaClientCertificateEnabledCheckBox;
        
        #line default
        #line hidden
        
        
        #line 338 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox InnolaClientCertificateStoreLocationTextBox;
        
        #line default
        #line hidden
        
        
        #line 349 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox InnolaClientCertificateStoreNameTextBox;
        
        #line default
        #line hidden
        
        
        #line 360 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox InnolaClientCertificateSubjectTextBox;
        
        #line default
        #line hidden
        
        
        #line 371 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox InnolaClientCertificateThumbprintTextBox;
        
        #line default
        #line hidden
        
        
        #line 375 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox InnolaAllowInvalidServerCertificateCheckBox;
        
        #line default
        #line hidden
        
        
        #line 378 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox InnolaCheckCertificateRevocationListCheckBox;
        
        #line default
        #line hidden
        
        
        #line 395 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox InnolaAttachmentUploadRouteTextBox;
        
        #line default
        #line hidden
        
        
        #line 406 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox InnolaAttachmentUploadBindingModeTextBox;
        
        #line default
        #line hidden
        
        
        #line 417 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox InnolaAttachmentUploadModeTextBox;
        
        #line default
        #line hidden
        
        
        #line 428 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox InnolaAttachmentUploadAuthModeTextBox;
        
        #line default
        #line hidden
        
        
        #line 439 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox InnolaResumeAttachmentSourceTypeTextBox;
        
        #line default
        #line hidden
        
        
        #line 450 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox InnolaCompletedAttachmentSourceTypeTextBox;
        
        #line default
        #line hidden
        
        
        #line 461 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox InnolaResumeAttachmentRegisteredTypeTextBox;
        
        #line default
        #line hidden
        
        
        #line 472 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox InnolaCompletedAttachmentRegisteredTypeTextBox;
        
        #line default
        #line hidden
        
        
        #line 483 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox InnolaAttachmentRegisteredSpatialUnitIdTextBox;
        
        #line default
        #line hidden
        
        
        #line 513 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox PreflightRulesPathTextBox;
        
        #line default
        #line hidden
        
        
        #line 520 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel PreflightRulesEditorPanel;
        
        #line default
        #line hidden
        
        
        #line 540 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox ReviewWorkspaceModeComboBox;
        
        #line default
        #line hidden
        
        
        #line 550 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock ReviewWorkspaceDescriptionTextBlock;
        
        #line default
        #line hidden
        
        
        #line 562 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox PdfViewerModeComboBox;
        
        #line default
        #line hidden
        
        
        #line 576 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox OutputTemplateProjectPathTextBox;
        
        #line default
        #line hidden
        
        
        #line 587 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox OutputTemplateGdbPathTextBox;
        
        #line default
        #line hidden
        
        
        #line 595 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox SpatialOutputAddCogoAttributesCheckBox;
        
        #line default
        #line hidden
        
        
        #line 599 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox SpatialOutputAddCogoLabelsCheckBox;
        
        #line default
        #line hidden
        
        
        #line 610 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox SpatialOutputCogoSourceModeComboBox;
        
        #line default
        #line hidden
        
        
        #line 643 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox OrientationNormalizationModeComboBox;
        
        #line default
        #line hidden
        
        
        #line 660 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox PreferredOutputOrientationComboBox;
        
        #line default
        #line hidden
        
        
        #line 677 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox BearingConsistencyToleranceTextBox;
        
        #line default
        #line hidden
        
        
        #line 690 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox BearingConsistencyWarningToleranceTextBox;
        
        #line default
        #line hidden
        
        
        #line 698 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox OrientationValidationProfileOverridesTextBox;
        
        #line default
        #line hidden
        
        
        #line 727 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox ClosureDefaultMaxClosureDistanceTextBox;
        
        #line default
        #line hidden
        
        
        #line 740 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox ClosureDefaultWarningClosureDistanceTextBox;
        
        #line default
        #line hidden
        
        
        #line 753 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox ClosureDefaultMinMiscloseRatioTextBox;
        
        #line default
        #line hidden
        
        
        #line 766 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox ClosureDefaultWarningMiscloseRatioTextBox;
        
        #line default
        #line hidden
        
        
        #line 779 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox ClosureToleranceProfileOverridesTextBox;
        
        #line default
        #line hidden
        
        
        #line 818 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox ReadinessDefaultParcelTypeTextBox;
        
        #line default
        #line hidden
        
        
        #line 822 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox ReadinessDefaultEnabledCheckBox;
        
        #line default
        #line hidden
        
        
        #line 835 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox ReadinessDefaultSeverityComboBox;
        
        #line default
        #line hidden
        
        
        #line 852 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox ReadinessDefaultMinSegmentCountTextBox;
        
        #line default
        #line hidden
        
        
        #line 857 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox ReadinessDefaultRequireContiguousSequenceCheckBox;
        
        #line default
        #line hidden
        
        
        #line 860 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox ReadinessDefaultRequireReferencedPointsCheckBox;
        
        #line default
        #line hidden
        
        
        #line 863 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox ReadinessDefaultRequireChainConsistencyCheckBox;
        
        #line default
        #line hidden
        
        
        #line 866 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox ReadinessDefaultDetectDuplicateEdgesCheckBox;
        
        #line default
        #line hidden
        
        
        #line 884 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel ReadinessRulesEditorPanel;
        
        #line default
        #line hidden
        
        
        #line 889 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Expander EnterpriseWorkingExpander;
        
        #line default
        #line hidden
        
        
        #line 892 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox EnterpriseWorkingEnabledCheckBox;
        
        #line default
        #line hidden
        
        
        #line 903 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox EnterpriseWorkingServiceRootTextBox;
        
        #line default
        #line hidden
        
        
        #line 914 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox EnterpriseWorkingWorkspaceNameTextBox;
        
        #line default
        #line hidden
        
        
        #line 925 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox EnterpriseWorkingPublishBehaviorComboBox;
        
        #line default
        #line hidden
        
        
        #line 939 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox EnterpriseWorkingPublishTimingComboBox;
        
        #line default
        #line hidden
        
        
        #line 953 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox EnterpriseWorkingRestoreBehaviorComboBox;
        
        #line default
        #line hidden
        
        
        #line 961 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox EnterpriseWorkingAllowCrossMachineRestoreCheckBox;
        
        #line default
        #line hidden
        
        
        #line 972 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox EnterpriseWorkingTransactionScopeFieldTextBox;
        
        #line default
        #line hidden
        
        
        #line 983 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox EnterpriseWorkingPointsLayerTextBox;
        
        #line default
        #line hidden
        
        
        #line 994 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox EnterpriseWorkingLinesLayerTextBox;
        
        #line default
        #line hidden
        
        
        #line 1005 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox EnterpriseWorkingPolygonsLayerTextBox;
        
        #line default
        #line hidden
        
        
        #line 1016 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox EnterpriseWorkingIssuesLayerTextBox;
        
        #line default
        #line hidden
        
        
        #line 1027 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox EnterpriseWorkingCaseIndexLayerTextBox;
        
        #line default
        #line hidden
        
        
        #line 1034 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Expander EnterpriseParcelFabricExpander;
        
        #line default
        #line hidden
        
        
        #line 1037 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox EnterpriseParcelFabricEnabledCheckBox;
        
        #line default
        #line hidden
        
        
        #line 1048 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox EnterpriseParcelFabricServiceRootTextBox;
        
        #line default
        #line hidden
        
        
        #line 1059 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox EnterpriseParcelFabricFabricLayerUrlTextBox;
        
        #line default
        #line hidden
        
        
        #line 1070 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox EnterpriseParcelFabricParcelLayerUrlTextBox;
        
        #line default
        #line hidden
        
        
        #line 1081 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox EnterpriseParcelFabricRecordsLayerUrlTextBox;
        
        #line default
        #line hidden
        
        
        #line 1092 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox EnterpriseParcelFabricParcelTypeNameTextBox;
        
        #line default
        #line hidden
        
        
        #line 1103 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox EnterpriseParcelFabricRecordNamePatternTextBox;
        
        #line default
        #line hidden
        
        
        #line 1114 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox EnterpriseParcelFabricTransactionScopeFieldTextBox;
        
        #line default
        #line hidden
        
        
        #line 1125 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox EnterpriseParcelFabricTransactionIdFieldTextBox;
        
        #line default
        #line hidden
        
        
        #line 1136 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox EnterpriseParcelFabricReviewStateFieldTextBox;
        
        #line default
        #line hidden
        
        
        #line 1147 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox EnterpriseParcelFabricPublishTimingComboBox;
        
        #line default
        #line hidden
        
        
        #line 1161 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox EnterpriseParcelFabricBuildBehaviorComboBox;
        
        #line default
        #line hidden
        
        
        #line 1168 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox EnterpriseParcelFabricLoadOverlaysCheckBox;
        
        #line default
        #line hidden
        
        
        #line 1179 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox EnterpriseParcelFabricOverlaySourceComboBox;
        
        #line default
        #line hidden
        
        
        #line 1186 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox EnterpriseParcelFabricAllowReplaceTransactionScopeCheckBox;
        
        #line default
        #line hidden
        
        
        #line 1190 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox EnterpriseParcelFabricRequireActiveMapCheckBox;
        
        #line default
        #line hidden
        
        
        #line 1207 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox GsiServerUrlTextBox;
        
        #line default
        #line hidden
        
        
        #line 1218 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox GsiUsernameTextBox;
        
        #line default
        #line hidden
        
        
        #line 1229 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox GsiPasswordModeComboBox;
        
        #line default
        #line hidden
        
        
        #line 1244 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox GsiPasswordEnvironmentVariableTextBox;
        
        #line default
        #line hidden
        
        
        #line 1255 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.PasswordBox GsiPasswordBox;
        
        #line default
        #line hidden
        
        
        #line 1281 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid WorkingMapLayersGrid;
        
        #line default
        #line hidden
        
        
        #line 1338 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox CompareSpatialSearchModeComboBox;
        
        #line default
        #line hidden
        
        
        #line 1349 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox CompareBufferDistanceMetersTextBox;
        
        #line default
        #line hidden
        
        
        #line 1374 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListView ParcelSearchSourceSummaryListView;
        
        #line default
        #line hidden
        
        
        #line 1408 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox CompareEnterpriseCadasterSourcesTextBox;
        
        #line default
        #line hidden
        
        
        #line 1441 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock EnterpriseAdminRuntimeSummaryTextBlock;
        
        #line default
        #line hidden
        
        
        #line 1448 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox EnterpriseAdminProvisioningEnabledCheckBox;
        
        #line default
        #line hidden
        
        
        #line 1459 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox EnterpriseAdminProvisioningScriptPathTextBox;
        
        #line default
        #line hidden
        
        
        #line 1470 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox EnterpriseAdminPortalUrlTextBox;
        
        #line default
        #line hidden
        
        
        #line 1481 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox EnterpriseAdminSchemaVersionTextBox;
        
        #line default
        #line hidden
        
        
        #line 1492 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox EnterpriseAdminTargetFolderTextBox;
        
        #line default
        #line hidden
        
        
        #line 1503 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox EnterpriseAdminTargetServiceNameTextBox;
        
        #line default
        #line hidden
        
        
        #line 1507 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox EnterpriseAdminAllowSettingsWritebackCheckBox;
        
        #line default
        #line hidden
        
        
        #line 1518 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox EnterpriseAdminCleanupModeComboBox;
        
        #line default
        #line hidden
        
        
        #line 1525 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox EnterpriseAdminRequireCleanupScopeCheckBox;
        
        #line default
        #line hidden
        
        
        #line 1536 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox EnterpriseAdminCleanupScopeTextBox;
        
        #line default
        #line hidden
        
        
        #line 1547 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox EnterpriseAdminLastValidationSummaryPathTextBox;
        
        #line default
        #line hidden
        
        
        #line 1558 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox EnterpriseAdminLastMaintenanceAuditPathTextBox;
        
        #line default
        #line hidden
        
        
        #line 1582 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock EnterpriseAdminStatusTextBlock;
        
        #line default
        #line hidden
        
        
        #line 1598 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock ValidationSummaryTextBlock;
        
        #line default
        #line hidden
        
        
        #line 1602 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock FooterStatusTextBlock;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.7.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/ParcelWorkflowAddIn;V1.1.310.0;component/configurationwindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.7.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.SettingsSummaryText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 2:
            this.SettingsTabControl = ((System.Windows.Controls.TabControl)(target));
            return;
            case 3:
            this.SettingsPathTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 4:
            this.CaseFolderRootTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 5:
            this.PythonExecutableTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 6:
            this.OutputAdapterScriptPathTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 7:
            this.ValidationAdapterScriptPathTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 8:
            this.ValidationRulesPathTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 9:
            this.OutputAdapterTimeoutTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 10:
            this.SdkLaneSummaryTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 11:
            this.OcrEngineComboBox = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 12:
            this.OpenAiEnabledCheckBox = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 13:
            this.OpenAiExtractionProfileComboBox = ((System.Windows.Controls.ComboBox)(target));
            
            #line 175 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
            this.OpenAiExtractionProfileComboBox.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.OpenAiExtractionProfileComboBox_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 14:
            this.OpenAiModelTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 15:
            this.OpenAiApiKeyEnvironmentVariableTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 16:
            this.InnolaServerUrlTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 17:
            this.InnolaModeComboBox = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 18:
            this.InnolaProcessStepTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 19:
            this.SupportedTransactionTypesTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 20:
            this.ComputeAttachmentSourceTypesTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 21:
            this.ComputeTransactionTypeProfilesTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 22:
            this.ComputeWorkflowStagesTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 23:
            this.InnolaClientCertificateEnabledCheckBox = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 24:
            this.InnolaClientCertificateStoreLocationTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 25:
            this.InnolaClientCertificateStoreNameTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 26:
            this.InnolaClientCertificateSubjectTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 27:
            this.InnolaClientCertificateThumbprintTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 28:
            this.InnolaAllowInvalidServerCertificateCheckBox = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 29:
            this.InnolaCheckCertificateRevocationListCheckBox = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 30:
            this.InnolaAttachmentUploadRouteTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 31:
            this.InnolaAttachmentUploadBindingModeTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 32:
            this.InnolaAttachmentUploadModeTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 33:
            this.InnolaAttachmentUploadAuthModeTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 34:
            this.InnolaResumeAttachmentSourceTypeTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 35:
            this.InnolaCompletedAttachmentSourceTypeTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 36:
            this.InnolaResumeAttachmentRegisteredTypeTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 37:
            this.InnolaCompletedAttachmentRegisteredTypeTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 38:
            this.InnolaAttachmentRegisteredSpatialUnitIdTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 39:
            this.PreflightRulesPathTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 40:
            this.PreflightRulesEditorPanel = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 41:
            this.ReviewWorkspaceModeComboBox = ((System.Windows.Controls.ComboBox)(target));
            
            #line 541 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
            this.ReviewWorkspaceModeComboBox.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.ReviewWorkspaceModeComboBox_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 42:
            this.ReviewWorkspaceDescriptionTextBlock = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 43:
            this.PdfViewerModeComboBox = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 44:
            this.OutputTemplateProjectPathTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 45:
            this.OutputTemplateGdbPathTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 46:
            this.SpatialOutputAddCogoAttributesCheckBox = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 47:
            this.SpatialOutputAddCogoLabelsCheckBox = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 48:
            this.SpatialOutputCogoSourceModeComboBox = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 49:
            this.OrientationNormalizationModeComboBox = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 50:
            this.PreferredOutputOrientationComboBox = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 51:
            this.BearingConsistencyToleranceTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 52:
            this.BearingConsistencyWarningToleranceTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 53:
            this.OrientationValidationProfileOverridesTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 54:
            this.ClosureDefaultMaxClosureDistanceTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 55:
            this.ClosureDefaultWarningClosureDistanceTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 56:
            this.ClosureDefaultMinMiscloseRatioTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 57:
            this.ClosureDefaultWarningMiscloseRatioTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 58:
            this.ClosureToleranceProfileOverridesTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 59:
            this.ReadinessDefaultParcelTypeTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 60:
            this.ReadinessDefaultEnabledCheckBox = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 61:
            this.ReadinessDefaultSeverityComboBox = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 62:
            this.ReadinessDefaultMinSegmentCountTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 63:
            this.ReadinessDefaultRequireContiguousSequenceCheckBox = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 64:
            this.ReadinessDefaultRequireReferencedPointsCheckBox = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 65:
            this.ReadinessDefaultRequireChainConsistencyCheckBox = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 66:
            this.ReadinessDefaultDetectDuplicateEdgesCheckBox = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 67:
            this.ReadinessRulesEditorPanel = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 68:
            this.EnterpriseWorkingExpander = ((System.Windows.Controls.Expander)(target));
            return;
            case 69:
            this.EnterpriseWorkingEnabledCheckBox = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 70:
            this.EnterpriseWorkingServiceRootTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 71:
            this.EnterpriseWorkingWorkspaceNameTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 72:
            this.EnterpriseWorkingPublishBehaviorComboBox = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 73:
            this.EnterpriseWorkingPublishTimingComboBox = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 74:
            this.EnterpriseWorkingRestoreBehaviorComboBox = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 75:
            this.EnterpriseWorkingAllowCrossMachineRestoreCheckBox = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 76:
            this.EnterpriseWorkingTransactionScopeFieldTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 77:
            this.EnterpriseWorkingPointsLayerTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 78:
            this.EnterpriseWorkingLinesLayerTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 79:
            this.EnterpriseWorkingPolygonsLayerTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 80:
            this.EnterpriseWorkingIssuesLayerTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 81:
            this.EnterpriseWorkingCaseIndexLayerTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 82:
            this.EnterpriseParcelFabricExpander = ((System.Windows.Controls.Expander)(target));
            return;
            case 83:
            this.EnterpriseParcelFabricEnabledCheckBox = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 84:
            this.EnterpriseParcelFabricServiceRootTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 85:
            this.EnterpriseParcelFabricFabricLayerUrlTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 86:
            this.EnterpriseParcelFabricParcelLayerUrlTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 87:
            this.EnterpriseParcelFabricRecordsLayerUrlTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 88:
            this.EnterpriseParcelFabricParcelTypeNameTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 89:
            this.EnterpriseParcelFabricRecordNamePatternTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 90:
            this.EnterpriseParcelFabricTransactionScopeFieldTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 91:
            this.EnterpriseParcelFabricTransactionIdFieldTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 92:
            this.EnterpriseParcelFabricReviewStateFieldTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 93:
            this.EnterpriseParcelFabricPublishTimingComboBox = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 94:
            this.EnterpriseParcelFabricBuildBehaviorComboBox = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 95:
            this.EnterpriseParcelFabricLoadOverlaysCheckBox = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 96:
            this.EnterpriseParcelFabricOverlaySourceComboBox = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 97:
            this.EnterpriseParcelFabricAllowReplaceTransactionScopeCheckBox = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 98:
            this.EnterpriseParcelFabricRequireActiveMapCheckBox = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 99:
            this.GsiServerUrlTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 100:
            this.GsiUsernameTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 101:
            this.GsiPasswordModeComboBox = ((System.Windows.Controls.ComboBox)(target));
            
            #line 1230 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
            this.GsiPasswordModeComboBox.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.GsiPasswordModeComboBox_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 102:
            this.GsiPasswordEnvironmentVariableTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 103:
            this.GsiPasswordBox = ((System.Windows.Controls.PasswordBox)(target));
            return;
            case 104:
            this.WorkingMapLayersGrid = ((System.Windows.Controls.DataGrid)(target));
            return;
            case 105:
            this.CompareSpatialSearchModeComboBox = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 106:
            this.CompareBufferDistanceMetersTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 107:
            this.ParcelSearchSourceSummaryListView = ((System.Windows.Controls.ListView)(target));
            return;
            case 108:
            this.CompareEnterpriseCadasterSourcesTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 109:
            this.EnterpriseAdminRuntimeSummaryTextBlock = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 110:
            this.EnterpriseAdminProvisioningEnabledCheckBox = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 111:
            this.EnterpriseAdminProvisioningScriptPathTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 112:
            this.EnterpriseAdminPortalUrlTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 113:
            this.EnterpriseAdminSchemaVersionTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 114:
            this.EnterpriseAdminTargetFolderTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 115:
            this.EnterpriseAdminTargetServiceNameTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 116:
            this.EnterpriseAdminAllowSettingsWritebackCheckBox = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 117:
            this.EnterpriseAdminCleanupModeComboBox = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 118:
            this.EnterpriseAdminRequireCleanupScopeCheckBox = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 119:
            this.EnterpriseAdminCleanupScopeTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 120:
            this.EnterpriseAdminLastValidationSummaryPathTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 121:
            this.EnterpriseAdminLastMaintenanceAuditPathTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 122:
            
            #line 1568 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.ValidateEnterpriseWorkingAdminButton_Click);
            
            #line default
            #line hidden
            return;
            case 123:
            
            #line 1572 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.ProvisionEnterpriseWorkingAdminButton_Click);
            
            #line default
            #line hidden
            return;
            case 124:
            
            #line 1575 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.CleanupEnterpriseWorkingAdminButton_Click);
            
            #line default
            #line hidden
            return;
            case 125:
            this.EnterpriseAdminStatusTextBlock = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 126:
            this.ValidationSummaryTextBlock = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 127:
            this.FooterStatusTextBlock = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 128:
            
            #line 1616 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.ReloadButton_Click);
            
            #line default
            #line hidden
            return;
            case 129:
            
            #line 1621 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.SaveButton_Click);
            
            #line default
            #line hidden
            return;
            case 130:
            
            #line 1625 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\ConfigurationWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.CloseButton_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

