#pragma checksum "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\JamaicaReviewWorkspaceWindow.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "307B2F519E46BB9C95CB996C0176DFB8EFB71C85"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using ArcGIS.Desktop.Framework.Controls;
using Microsoft.Web.WebView2.Wpf;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace ParcelWorkflowAddIn {
    
    
    internal partial class JamaicaReviewWorkspaceWindow : ArcGIS.Desktop.Framework.Controls.ProWindow, System.Windows.Markup.IComponentConnector, System.Windows.Markup.IStyleConnector {
        
        
        #line 334 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\JamaicaReviewWorkspaceWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Microsoft.Web.WebView2.Wpf.WebView2 ViewerPdfWebView;
        
        #line default
        #line hidden
        
        
        #line 466 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\JamaicaReviewWorkspaceWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid StandardReviewPointsGrid;
        
        #line default
        #line hidden
        
        
        #line 549 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\JamaicaReviewWorkspaceWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid StandardReviewSegmentsGrid;
        
        #line default
        #line hidden
        
        
        #line 611 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\JamaicaReviewWorkspaceWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabControl ReviewTabs;
        
        #line default
        #line hidden
        
        
        #line 635 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\JamaicaReviewWorkspaceWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid PxaMetadataGrid;
        
        #line default
        #line hidden
        
        
        #line 677 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\JamaicaReviewWorkspaceWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid PxaVolumeFolioGrid;
        
        #line default
        #line hidden
        
        
        #line 845 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\JamaicaReviewWorkspaceWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid PxaNamedPartiesGrid;
        
        #line default
        #line hidden
        
        
        #line 884 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\JamaicaReviewWorkspaceWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid PxaAdjacentOwnersGrid;
        
        #line default
        #line hidden
        
        
        #line 975 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\JamaicaReviewWorkspaceWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid PxaBoundarySegmentsGrid;
        
        #line default
        #line hidden
        
        
        #line 1067 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\JamaicaReviewWorkspaceWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid PxaPointsGrid;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.7.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/ParcelWorkflowAddIn;V1.1.310.0;component/jamaicareviewworkspacewindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\JamaicaReviewWorkspaceWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.7.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.ViewerPdfWebView = ((Microsoft.Web.WebView2.Wpf.WebView2)(target));
            return;
            case 2:
            
            #line 428 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\JamaicaReviewWorkspaceWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.RemovePointButton_Click);
            
            #line default
            #line hidden
            return;
            case 3:
            this.StandardReviewPointsGrid = ((System.Windows.Controls.DataGrid)(target));
            
            #line 470 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\JamaicaReviewWorkspaceWindow.xaml"
            this.StandardReviewPointsGrid.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.ReviewDataGrid_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 4:
            this.StandardReviewSegmentsGrid = ((System.Windows.Controls.DataGrid)(target));
            
            #line 553 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\JamaicaReviewWorkspaceWindow.xaml"
            this.StandardReviewSegmentsGrid.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.ReviewDataGrid_SelectionChanged);
            
            #line default
            #line hidden
            
            #line 557 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\JamaicaReviewWorkspaceWindow.xaml"
            this.StandardReviewSegmentsGrid.MouseDoubleClick += new System.Windows.Input.MouseButtonEventHandler(this.SegmentGrid_MouseDoubleClick);
            
            #line default
            #line hidden
            return;
            case 5:
            this.ReviewTabs = ((System.Windows.Controls.TabControl)(target));
            
            #line 614 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\JamaicaReviewWorkspaceWindow.xaml"
            this.ReviewTabs.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.ReviewTabs_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 6:
            this.PxaMetadataGrid = ((System.Windows.Controls.DataGrid)(target));
            
            #line 638 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\JamaicaReviewWorkspaceWindow.xaml"
            this.PxaMetadataGrid.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.ReviewDataGrid_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 7:
            this.PxaVolumeFolioGrid = ((System.Windows.Controls.DataGrid)(target));
            
            #line 680 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\JamaicaReviewWorkspaceWindow.xaml"
            this.PxaVolumeFolioGrid.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.ReviewDataGrid_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 9:
            this.PxaNamedPartiesGrid = ((System.Windows.Controls.DataGrid)(target));
            
            #line 848 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\JamaicaReviewWorkspaceWindow.xaml"
            this.PxaNamedPartiesGrid.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.ReviewDataGrid_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 10:
            this.PxaAdjacentOwnersGrid = ((System.Windows.Controls.DataGrid)(target));
            
            #line 887 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\JamaicaReviewWorkspaceWindow.xaml"
            this.PxaAdjacentOwnersGrid.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.ReviewDataGrid_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 11:
            this.PxaBoundarySegmentsGrid = ((System.Windows.Controls.DataGrid)(target));
            
            #line 979 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\JamaicaReviewWorkspaceWindow.xaml"
            this.PxaBoundarySegmentsGrid.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.ReviewDataGrid_SelectionChanged);
            
            #line default
            #line hidden
            
            #line 981 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\JamaicaReviewWorkspaceWindow.xaml"
            this.PxaBoundarySegmentsGrid.MouseDoubleClick += new System.Windows.Input.MouseButtonEventHandler(this.SegmentGrid_MouseDoubleClick);
            
            #line default
            #line hidden
            return;
            case 12:
            
            #line 1056 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\JamaicaReviewWorkspaceWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.RemovePointButton_Click);
            
            #line default
            #line hidden
            return;
            case 13:
            this.PxaPointsGrid = ((System.Windows.Controls.DataGrid)(target));
            
            #line 1071 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\JamaicaReviewWorkspaceWindow.xaml"
            this.PxaPointsGrid.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.ReviewDataGrid_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 14:
            
            #line 1400 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\JamaicaReviewWorkspaceWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.ValidationCompleteButton_Click);
            
            #line default
            #line hidden
            return;
            case 15:
            
            #line 1406 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\JamaicaReviewWorkspaceWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.SaveButton_Click);
            
            #line default
            #line hidden
            return;
            case 16:
            
            #line 1409 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\JamaicaReviewWorkspaceWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.CloseButton_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.7.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        void System.Windows.Markup.IStyleConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 8:
            
            #line 743 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\JamaicaReviewWorkspaceWindow.xaml"
            ((System.Windows.Controls.DataGrid)(target)).SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.ReviewDataGrid_SelectionChanged);
            
            #line default
            #line hidden
            break;
            }
        }
    }
}

