#pragma checksum "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\TransactionDocumentsWindow.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "9A8C1119D606F25E22F2C04AC43CE345065DCAB0"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using ArcGIS.Desktop.Framework.Controls;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace ParcelWorkflowAddIn {
    
    
    /// <summary>
    /// TransactionDocumentsWindow
    /// </summary>
    public partial class TransactionDocumentsWindow : ArcGIS.Desktop.Framework.Controls.ProWindow, System.Windows.Markup.IComponentConnector {
        
        
        #line 17 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\TransactionDocumentsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TransactionText;
        
        #line default
        #line hidden
        
        
        #line 20 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\TransactionDocumentsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock FolderText;
        
        #line default
        #line hidden
        
        
        #line 26 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\TransactionDocumentsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabControl DocumentsTabs;
        
        #line default
        #line hidden
        
        
        #line 28 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\TransactionDocumentsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabItem SourceTab;
        
        #line default
        #line hidden
        
        
        #line 30 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\TransactionDocumentsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListView SourceDocumentsList;
        
        #line default
        #line hidden
        
        
        #line 43 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\TransactionDocumentsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabItem OutputTab;
        
        #line default
        #line hidden
        
        
        #line 45 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\TransactionDocumentsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListView OutputDocumentsList;
        
        #line default
        #line hidden
        
        
        #line 69 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\TransactionDocumentsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock StatusText;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.7.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/ParcelWorkflowAddIn;V1.1.310.0;component/transactiondocumentswindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\TransactionDocumentsWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.7.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.TransactionText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 2:
            this.FolderText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 3:
            this.DocumentsTabs = ((System.Windows.Controls.TabControl)(target));
            return;
            case 4:
            this.SourceTab = ((System.Windows.Controls.TabItem)(target));
            return;
            case 5:
            this.SourceDocumentsList = ((System.Windows.Controls.ListView)(target));
            return;
            case 6:
            this.OutputTab = ((System.Windows.Controls.TabItem)(target));
            return;
            case 7:
            this.OutputDocumentsList = ((System.Windows.Controls.ListView)(target));
            return;
            case 8:
            this.StatusText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 9:
            
            #line 77 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\TransactionDocumentsWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.OpenButton_Click);
            
            #line default
            #line hidden
            return;
            case 10:
            
            #line 82 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\TransactionDocumentsWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.RefreshButton_Click);
            
            #line default
            #line hidden
            return;
            case 11:
            
            #line 87 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\TransactionDocumentsWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.FolderButton_Click);
            
            #line default
            #line hidden
            return;
            case 12:
            
            #line 92 "..\..\..\..\..\..\..\src\ParcelWorkflowAddIn\ParcelWorkflowAddIn\TransactionDocumentsWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.CloseButton_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

